/*
    Easy
    Copyright (C) 2019 Università degli Studi di Catania (www.unict.it)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

ï»¿//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace inventorytreeview_tree {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class vistaForm : DataSet {
        
        private inventorysortinglevelDataTable tableinventorysortinglevel;
        
        private inventorytreeviewDataTable tableinventorytreeview;
        
        private DataRelation relationinventorytreeviewinventorytreeview;
        
        private DataRelation relationinventorysortinglevelinventorytreeview;
        
        public vistaForm() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected vistaForm(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["inventorysortinglevel"] != null)) {
                    this.Tables.Add(new inventorysortinglevelDataTable(ds.Tables["inventorysortinglevel"]));
                }
                if ((ds.Tables["inventorytreeview"] != null)) {
                    this.Tables.Add(new inventorytreeviewDataTable(ds.Tables["inventorytreeview"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public inventorysortinglevelDataTable inventorysortinglevel {
            get {
                return this.tableinventorysortinglevel;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public inventorytreeviewDataTable inventorytreeview {
            get {
                return this.tableinventorytreeview;
            }
        }
        
        public override DataSet Clone() {
            vistaForm cln = ((vistaForm)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["inventorysortinglevel"] != null)) {
                this.Tables.Add(new inventorysortinglevelDataTable(ds.Tables["inventorysortinglevel"]));
            }
            if ((ds.Tables["inventorytreeview"] != null)) {
                this.Tables.Add(new inventorytreeviewDataTable(ds.Tables["inventorytreeview"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableinventorysortinglevel = ((inventorysortinglevelDataTable)(this.Tables["inventorysortinglevel"]));
            if ((this.tableinventorysortinglevel != null)) {
                this.tableinventorysortinglevel.InitVars();
            }
            this.tableinventorytreeview = ((inventorytreeviewDataTable)(this.Tables["inventorytreeview"]));
            if ((this.tableinventorytreeview != null)) {
                this.tableinventorytreeview.InitVars();
            }
            this.relationinventorytreeviewinventorytreeview = this.Relations["inventorytreeviewinventorytreeview"];
            this.relationinventorysortinglevelinventorytreeview = this.Relations["inventorysortinglevelinventorytreeview"];
        }
        
        private void InitClass() {
            this.DataSetName = "vistaForm";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/VistaClassInventarioViewTree.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableinventorysortinglevel = new inventorysortinglevelDataTable();
            this.Tables.Add(this.tableinventorysortinglevel);
            this.tableinventorytreeview = new inventorytreeviewDataTable();
            this.Tables.Add(this.tableinventorytreeview);
            ForeignKeyConstraint fkc;
            fkc = new ForeignKeyConstraint("vistaFormKey4", new DataColumn[] {
                        this.tableinventorytreeview.idinvColumn}, new DataColumn[] {
                        this.tableinventorytreeview.paridinvColumn});
            this.tableinventorytreeview.Constraints.Add(fkc);
            fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
            fkc.DeleteRule = System.Data.Rule.Cascade;
            fkc.UpdateRule = System.Data.Rule.Cascade;
            fkc = new ForeignKeyConstraint("vistaFormKey3", new DataColumn[] {
                        this.tableinventorysortinglevel.nlevelColumn}, new DataColumn[] {
                        this.tableinventorytreeview.nlevelColumn});
            this.tableinventorytreeview.Constraints.Add(fkc);
            fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
            fkc.DeleteRule = System.Data.Rule.Cascade;
            fkc.UpdateRule = System.Data.Rule.Cascade;
            this.relationinventorytreeviewinventorytreeview = new DataRelation("inventorytreeviewinventorytreeview", new DataColumn[] {
                        this.tableinventorytreeview.idinvColumn}, new DataColumn[] {
                        this.tableinventorytreeview.paridinvColumn}, false);
            this.Relations.Add(this.relationinventorytreeviewinventorytreeview);
            this.relationinventorysortinglevelinventorytreeview = new DataRelation("inventorysortinglevelinventorytreeview", new DataColumn[] {
                        this.tableinventorysortinglevel.nlevelColumn}, new DataColumn[] {
                        this.tableinventorytreeview.nlevelColumn}, false);
            this.Relations.Add(this.relationinventorysortinglevelinventorytreeview);
        }
        
        private bool ShouldSerializeinventorysortinglevel() {
            return false;
        }
        
        private bool ShouldSerializeinventorytreeview() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void inventorysortinglevelRowChangeEventHandler(object sender, inventorysortinglevelRowChangeEvent e);
        
        public delegate void inventorytreeviewRowChangeEventHandler(object sender, inventorytreeviewRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class inventorysortinglevelDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnnlevel;
            
            private DataColumn columndescription;
            
            private DataColumn columncodekind;
            
            private DataColumn columncodelen;
            
            private DataColumn columnflagrestart;
            
            private DataColumn columnflagusable;
            
            private DataColumn columncu;
            
            private DataColumn columnct;
            
            private DataColumn columnlu;
            
            private DataColumn columnlt;
            
            internal inventorysortinglevelDataTable() : 
                    base("inventorysortinglevel") {
                this.InitClass();
            }
            
            internal inventorysortinglevelDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn nlevelColumn {
                get {
                    return this.columnnlevel;
                }
            }
            
            internal DataColumn descriptionColumn {
                get {
                    return this.columndescription;
                }
            }
            
            internal DataColumn codekindColumn {
                get {
                    return this.columncodekind;
                }
            }
            
            internal DataColumn codelenColumn {
                get {
                    return this.columncodelen;
                }
            }
            
            internal DataColumn flagrestartColumn {
                get {
                    return this.columnflagrestart;
                }
            }
            
            internal DataColumn flagusableColumn {
                get {
                    return this.columnflagusable;
                }
            }
            
            internal DataColumn cuColumn {
                get {
                    return this.columncu;
                }
            }
            
            internal DataColumn ctColumn {
                get {
                    return this.columnct;
                }
            }
            
            internal DataColumn luColumn {
                get {
                    return this.columnlu;
                }
            }
            
            internal DataColumn ltColumn {
                get {
                    return this.columnlt;
                }
            }
            
            public inventorysortinglevelRow this[int index] {
                get {
                    return ((inventorysortinglevelRow)(this.Rows[index]));
                }
            }
            
            public event inventorysortinglevelRowChangeEventHandler inventorysortinglevelRowChanged;
            
            public event inventorysortinglevelRowChangeEventHandler inventorysortinglevelRowChanging;
            
            public event inventorysortinglevelRowChangeEventHandler inventorysortinglevelRowDeleted;
            
            public event inventorysortinglevelRowChangeEventHandler inventorysortinglevelRowDeleting;
            
            public void AddinventorysortinglevelRow(inventorysortinglevelRow row) {
                this.Rows.Add(row);
            }
            
            public inventorysortinglevelRow AddinventorysortinglevelRow(string nlevel, string description, string codekind, short codelen, string flagrestart, string flagusable, string cu, System.DateTime ct, string lu, System.DateTime lt) {
                inventorysortinglevelRow rowinventorysortinglevelRow = ((inventorysortinglevelRow)(this.NewRow()));
                rowinventorysortinglevelRow.ItemArray = new object[] {
                        nlevel,
                        description,
                        codekind,
                        codelen,
                        flagrestart,
                        flagusable,
                        cu,
                        ct,
                        lu,
                        lt};
                this.Rows.Add(rowinventorysortinglevelRow);
                return rowinventorysortinglevelRow;
            }
            
            public inventorysortinglevelRow FindBynlevel(string nlevel) {
                return ((inventorysortinglevelRow)(this.Rows.Find(new object[] {
                            nlevel})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                inventorysortinglevelDataTable cln = ((inventorysortinglevelDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new inventorysortinglevelDataTable();
            }
            
            internal void InitVars() {
                this.columnnlevel = this.Columns["nlevel"];
                this.columndescription = this.Columns["description"];
                this.columncodekind = this.Columns["codekind"];
                this.columncodelen = this.Columns["codelen"];
                this.columnflagrestart = this.Columns["flagrestart"];
                this.columnflagusable = this.Columns["flagusable"];
                this.columncu = this.Columns["cu"];
                this.columnct = this.Columns["ct"];
                this.columnlu = this.Columns["lu"];
                this.columnlt = this.Columns["lt"];
            }
            
            private void InitClass() {
                this.columnnlevel = new DataColumn("nlevel", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnlevel);
                this.columndescription = new DataColumn("description", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescription);
                this.columncodekind = new DataColumn("codekind", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncodekind);
                this.columncodelen = new DataColumn("codelen", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncodelen);
                this.columnflagrestart = new DataColumn("flagrestart", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnflagrestart);
                this.columnflagusable = new DataColumn("flagusable", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnflagusable);
                this.columncu = new DataColumn("cu", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncu);
                this.columnct = new DataColumn("ct", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnct);
                this.columnlu = new DataColumn("lu", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnlu);
                this.columnlt = new DataColumn("lt", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnlt);
                this.Constraints.Add(new UniqueConstraint("vistaFormKey1", new DataColumn[] {
                                this.columnnlevel}, true));
                this.columnnlevel.AllowDBNull = false;
                this.columnnlevel.Unique = true;
                this.columndescription.AllowDBNull = false;
                this.columncodekind.AllowDBNull = false;
                this.columncodelen.AllowDBNull = false;
                this.columnflagrestart.AllowDBNull = false;
                this.columnflagusable.AllowDBNull = false;
                this.columncu.AllowDBNull = false;
                this.columnct.AllowDBNull = false;
                this.columnlu.AllowDBNull = false;
                this.columnlt.AllowDBNull = false;
            }
            
            public inventorysortinglevelRow NewinventorysortinglevelRow() {
                return ((inventorysortinglevelRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new inventorysortinglevelRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(inventorysortinglevelRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.inventorysortinglevelRowChanged != null)) {
                    this.inventorysortinglevelRowChanged(this, new inventorysortinglevelRowChangeEvent(((inventorysortinglevelRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.inventorysortinglevelRowChanging != null)) {
                    this.inventorysortinglevelRowChanging(this, new inventorysortinglevelRowChangeEvent(((inventorysortinglevelRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.inventorysortinglevelRowDeleted != null)) {
                    this.inventorysortinglevelRowDeleted(this, new inventorysortinglevelRowChangeEvent(((inventorysortinglevelRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.inventorysortinglevelRowDeleting != null)) {
                    this.inventorysortinglevelRowDeleting(this, new inventorysortinglevelRowChangeEvent(((inventorysortinglevelRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveinventorysortinglevelRow(inventorysortinglevelRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class inventorysortinglevelRow : DataRow {
            
            private inventorysortinglevelDataTable tableinventorysortinglevel;
            
            internal inventorysortinglevelRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableinventorysortinglevel = ((inventorysortinglevelDataTable)(this.Table));
            }
            
            public string nlevel {
                get {
                    return ((string)(this[this.tableinventorysortinglevel.nlevelColumn]));
                }
                set {
                    this[this.tableinventorysortinglevel.nlevelColumn] = value;
                }
            }
            
            public string description {
                get {
                    return ((string)(this[this.tableinventorysortinglevel.descriptionColumn]));
                }
                set {
                    this[this.tableinventorysortinglevel.descriptionColumn] = value;
                }
            }
            
            public string codekind {
                get {
                    return ((string)(this[this.tableinventorysortinglevel.codekindColumn]));
                }
                set {
                    this[this.tableinventorysortinglevel.codekindColumn] = value;
                }
            }
            
            public short codelen {
                get {
                    return ((short)(this[this.tableinventorysortinglevel.codelenColumn]));
                }
                set {
                    this[this.tableinventorysortinglevel.codelenColumn] = value;
                }
            }
            
            public string flagrestart {
                get {
                    return ((string)(this[this.tableinventorysortinglevel.flagrestartColumn]));
                }
                set {
                    this[this.tableinventorysortinglevel.flagrestartColumn] = value;
                }
            }
            
            public string flagusable {
                get {
                    return ((string)(this[this.tableinventorysortinglevel.flagusableColumn]));
                }
                set {
                    this[this.tableinventorysortinglevel.flagusableColumn] = value;
                }
            }
            
            public string cu {
                get {
                    return ((string)(this[this.tableinventorysortinglevel.cuColumn]));
                }
                set {
                    this[this.tableinventorysortinglevel.cuColumn] = value;
                }
            }
            
            public System.DateTime ct {
                get {
                    return ((System.DateTime)(this[this.tableinventorysortinglevel.ctColumn]));
                }
                set {
                    this[this.tableinventorysortinglevel.ctColumn] = value;
                }
            }
            
            public string lu {
                get {
                    return ((string)(this[this.tableinventorysortinglevel.luColumn]));
                }
                set {
                    this[this.tableinventorysortinglevel.luColumn] = value;
                }
            }
            
            public System.DateTime lt {
                get {
                    return ((System.DateTime)(this[this.tableinventorysortinglevel.ltColumn]));
                }
                set {
                    this[this.tableinventorysortinglevel.ltColumn] = value;
                }
            }
            
            public inventorytreeviewRow[] GetinventorytreeviewRows() {
                return ((inventorytreeviewRow[])(this.GetChildRows(this.Table.ChildRelations["inventorysortinglevelinventorytreeview"])));
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class inventorysortinglevelRowChangeEvent : EventArgs {
            
            private inventorysortinglevelRow eventRow;
            
            private DataRowAction eventAction;
            
            public inventorysortinglevelRowChangeEvent(inventorysortinglevelRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public inventorysortinglevelRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class inventorytreeviewDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnidinv;
            
            private DataColumn columnnlevel;
            
            private DataColumn columnleveldescr;
            
            private DataColumn columncodeinv;
            
            private DataColumn columnparidinv;
            
            private DataColumn columndescription;
            
            private DataColumn columndescriptionstring1;
            
            private DataColumn columndescriptionstring2;
            
            private DataColumn columndescriptionstring3;
            
            private DataColumn columndescriptionstring4;
            
            private DataColumn columndescriptionstring5;
            
            private DataColumn columndescriptionstring6;
            
            private DataColumn columndescriptionstring7;
            
            private DataColumn columndescriptionstring8;
            
            private DataColumn columndescriptionstring9;
            
            private DataColumn columndescriptiondate1;
            
            private DataColumn columndescriptiondate2;
            
            private DataColumn columndescriptiondate3;
            
            private DataColumn columndescriptiondate4;
            
            private DataColumn columndescriptiondate5;
            
            private DataColumn columndescriptiondate6;
            
            private DataColumn columndescriptiondate7;
            
            private DataColumn columndescriptiondate8;
            
            private DataColumn columndescriptiondate9;
            
            private DataColumn columndescriptionint1;
            
            private DataColumn columndescriptionint2;
            
            private DataColumn columndescriptionint3;
            
            private DataColumn columndescriptionint4;
            
            private DataColumn columndescriptionint5;
            
            private DataColumn columndescriptionint6;
            
            private DataColumn columndescriptionint7;
            
            private DataColumn columndescriptionint8;
            
            private DataColumn columndescriptionint9;
            
            private DataColumn columndescriptionfloat1;
            
            private DataColumn columndescriptionfloat2;
            
            private DataColumn columndescriptionfloat3;
            
            private DataColumn columndescriptionfloat4;
            
            private DataColumn columndescriptionfloat5;
            
            private DataColumn columndescriptionfloat6;
            
            private DataColumn columndescriptionfloat7;
            
            private DataColumn columndescriptionfloat8;
            
            private DataColumn columndescriptionfloat9;
            
            private DataColumn columncu;
            
            private DataColumn columnct;
            
            private DataColumn columnlu;
            
            private DataColumn columnlt;
            
            internal inventorytreeviewDataTable() : 
                    base("inventorytreeview") {
                this.InitClass();
            }
            
            internal inventorytreeviewDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn idinvColumn {
                get {
                    return this.columnidinv;
                }
            }
            
            internal DataColumn nlevelColumn {
                get {
                    return this.columnnlevel;
                }
            }
            
            internal DataColumn leveldescrColumn {
                get {
                    return this.columnleveldescr;
                }
            }
            
            internal DataColumn codeinvColumn {
                get {
                    return this.columncodeinv;
                }
            }
            
            internal DataColumn paridinvColumn {
                get {
                    return this.columnparidinv;
                }
            }
            
            internal DataColumn descriptionColumn {
                get {
                    return this.columndescription;
                }
            }
            
            internal DataColumn descriptionstring1Column {
                get {
                    return this.columndescriptionstring1;
                }
            }
            
            internal DataColumn descriptionstring2Column {
                get {
                    return this.columndescriptionstring2;
                }
            }
            
            internal DataColumn descriptionstring3Column {
                get {
                    return this.columndescriptionstring3;
                }
            }
            
            internal DataColumn descriptionstring4Column {
                get {
                    return this.columndescriptionstring4;
                }
            }
            
            internal DataColumn descriptionstring5Column {
                get {
                    return this.columndescriptionstring5;
                }
            }
            
            internal DataColumn descriptionstring6Column {
                get {
                    return this.columndescriptionstring6;
                }
            }
            
            internal DataColumn descriptionstring7Column {
                get {
                    return this.columndescriptionstring7;
                }
            }
            
            internal DataColumn descriptionstring8Column {
                get {
                    return this.columndescriptionstring8;
                }
            }
            
            internal DataColumn descriptionstring9Column {
                get {
                    return this.columndescriptionstring9;
                }
            }
            
            internal DataColumn descriptiondate1Column {
                get {
                    return this.columndescriptiondate1;
                }
            }
            
            internal DataColumn descriptiondate2Column {
                get {
                    return this.columndescriptiondate2;
                }
            }
            
            internal DataColumn descriptiondate3Column {
                get {
                    return this.columndescriptiondate3;
                }
            }
            
            internal DataColumn descriptiondate4Column {
                get {
                    return this.columndescriptiondate4;
                }
            }
            
            internal DataColumn descriptiondate5Column {
                get {
                    return this.columndescriptiondate5;
                }
            }
            
            internal DataColumn descriptiondate6Column {
                get {
                    return this.columndescriptiondate6;
                }
            }
            
            internal DataColumn descriptiondate7Column {
                get {
                    return this.columndescriptiondate7;
                }
            }
            
            internal DataColumn descriptiondate8Column {
                get {
                    return this.columndescriptiondate8;
                }
            }
            
            internal DataColumn descriptiondate9Column {
                get {
                    return this.columndescriptiondate9;
                }
            }
            
            internal DataColumn descriptionint1Column {
                get {
                    return this.columndescriptionint1;
                }
            }
            
            internal DataColumn descriptionint2Column {
                get {
                    return this.columndescriptionint2;
                }
            }
            
            internal DataColumn descriptionint3Column {
                get {
                    return this.columndescriptionint3;
                }
            }
            
            internal DataColumn descriptionint4Column {
                get {
                    return this.columndescriptionint4;
                }
            }
            
            internal DataColumn descriptionint5Column {
                get {
                    return this.columndescriptionint5;
                }
            }
            
            internal DataColumn descriptionint6Column {
                get {
                    return this.columndescriptionint6;
                }
            }
            
            internal DataColumn descriptionint7Column {
                get {
                    return this.columndescriptionint7;
                }
            }
            
            internal DataColumn descriptionint8Column {
                get {
                    return this.columndescriptionint8;
                }
            }
            
            internal DataColumn descriptionint9Column {
                get {
                    return this.columndescriptionint9;
                }
            }
            
            internal DataColumn descriptionfloat1Column {
                get {
                    return this.columndescriptionfloat1;
                }
            }
            
            internal DataColumn descriptionfloat2Column {
                get {
                    return this.columndescriptionfloat2;
                }
            }
            
            internal DataColumn descriptionfloat3Column {
                get {
                    return this.columndescriptionfloat3;
                }
            }
            
            internal DataColumn descriptionfloat4Column {
                get {
                    return this.columndescriptionfloat4;
                }
            }
            
            internal DataColumn descriptionfloat5Column {
                get {
                    return this.columndescriptionfloat5;
                }
            }
            
            internal DataColumn descriptionfloat6Column {
                get {
                    return this.columndescriptionfloat6;
                }
            }
            
            internal DataColumn descriptionfloat7Column {
                get {
                    return this.columndescriptionfloat7;
                }
            }
            
            internal DataColumn descriptionfloat8Column {
                get {
                    return this.columndescriptionfloat8;
                }
            }
            
            internal DataColumn descriptionfloat9Column {
                get {
                    return this.columndescriptionfloat9;
                }
            }
            
            internal DataColumn cuColumn {
                get {
                    return this.columncu;
                }
            }
            
            internal DataColumn ctColumn {
                get {
                    return this.columnct;
                }
            }
            
            internal DataColumn luColumn {
                get {
                    return this.columnlu;
                }
            }
            
            internal DataColumn ltColumn {
                get {
                    return this.columnlt;
                }
            }
            
            public inventorytreeviewRow this[int index] {
                get {
                    return ((inventorytreeviewRow)(this.Rows[index]));
                }
            }
            
            public event inventorytreeviewRowChangeEventHandler inventorytreeviewRowChanged;
            
            public event inventorytreeviewRowChangeEventHandler inventorytreeviewRowChanging;
            
            public event inventorytreeviewRowChangeEventHandler inventorytreeviewRowDeleted;
            
            public event inventorytreeviewRowChangeEventHandler inventorytreeviewRowDeleting;
            
            public void AddinventorytreeviewRow(inventorytreeviewRow row) {
                this.Rows.Add(row);
            }
            
            public inventorytreeviewRow AddinventorytreeviewRow(
                        string idinv, 
                        inventorysortinglevelRow parentinventorysortinglevelRowByinventorysortinglevelinventorytreeview, 
                        string leveldescr, 
                        string codeinv, 
                        inventorytreeviewRow parentinventorytreeviewRowByinventorytreeviewinventorytreeview, 
                        string description, 
                        string descriptionstring1, 
                        string descriptionstring2, 
                        string descriptionstring3, 
                        string descriptionstring4, 
                        string descriptionstring5, 
                        string descriptionstring6, 
                        string descriptionstring7, 
                        string descriptionstring8, 
                        string descriptionstring9, 
                        string descriptiondate1, 
                        string descriptiondate2, 
                        string descriptiondate3, 
                        string descriptiondate4, 
                        string descriptiondate5, 
                        string descriptiondate6, 
                        string descriptiondate7, 
                        string descriptiondate8, 
                        string descriptiondate9, 
                        string descriptionint1, 
                        string descriptionint2, 
                        string descriptionint3, 
                        string descriptionint4, 
                        string descriptionint5, 
                        string descriptionint6, 
                        string descriptionint7, 
                        string descriptionint8, 
                        string descriptionint9, 
                        string descriptionfloat1, 
                        string descriptionfloat2, 
                        string descriptionfloat3, 
                        string descriptionfloat4, 
                        string descriptionfloat5, 
                        string descriptionfloat6, 
                        string descriptionfloat7, 
                        string descriptionfloat8, 
                        string descriptionfloat9, 
                        string cu, 
                        System.DateTime ct, 
                        string lu, 
                        System.DateTime lt) {
                inventorytreeviewRow rowinventorytreeviewRow = ((inventorytreeviewRow)(this.NewRow()));
                rowinventorytreeviewRow.ItemArray = new object[] {
                        idinv,
                        parentinventorysortinglevelRowByinventorysortinglevelinventorytreeview[0],
                        leveldescr,
                        codeinv,
                        parentinventorytreeviewRowByinventorytreeviewinventorytreeview[0],
                        description,
                        descriptionstring1,
                        descriptionstring2,
                        descriptionstring3,
                        descriptionstring4,
                        descriptionstring5,
                        descriptionstring6,
                        descriptionstring7,
                        descriptionstring8,
                        descriptionstring9,
                        descriptiondate1,
                        descriptiondate2,
                        descriptiondate3,
                        descriptiondate4,
                        descriptiondate5,
                        descriptiondate6,
                        descriptiondate7,
                        descriptiondate8,
                        descriptiondate9,
                        descriptionint1,
                        descriptionint2,
                        descriptionint3,
                        descriptionint4,
                        descriptionint5,
                        descriptionint6,
                        descriptionint7,
                        descriptionint8,
                        descriptionint9,
                        descriptionfloat1,
                        descriptionfloat2,
                        descriptionfloat3,
                        descriptionfloat4,
                        descriptionfloat5,
                        descriptionfloat6,
                        descriptionfloat7,
                        descriptionfloat8,
                        descriptionfloat9,
                        cu,
                        ct,
                        lu,
                        lt};
                this.Rows.Add(rowinventorytreeviewRow);
                return rowinventorytreeviewRow;
            }
            
            public inventorytreeviewRow FindByidinv(string idinv) {
                return ((inventorytreeviewRow)(this.Rows.Find(new object[] {
                            idinv})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                inventorytreeviewDataTable cln = ((inventorytreeviewDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new inventorytreeviewDataTable();
            }
            
            internal void InitVars() {
                this.columnidinv = this.Columns["idinv"];
                this.columnnlevel = this.Columns["nlevel"];
                this.columnleveldescr = this.Columns["leveldescr"];
                this.columncodeinv = this.Columns["codeinv"];
                this.columnparidinv = this.Columns["paridinv"];
                this.columndescription = this.Columns["description"];
                this.columndescriptionstring1 = this.Columns["descriptionstring1"];
                this.columndescriptionstring2 = this.Columns["descriptionstring2"];
                this.columndescriptionstring3 = this.Columns["descriptionstring3"];
                this.columndescriptionstring4 = this.Columns["descriptionstring4"];
                this.columndescriptionstring5 = this.Columns["descriptionstring5"];
                this.columndescriptionstring6 = this.Columns["descriptionstring6"];
                this.columndescriptionstring7 = this.Columns["descriptionstring7"];
                this.columndescriptionstring8 = this.Columns["descriptionstring8"];
                this.columndescriptionstring9 = this.Columns["descriptionstring9"];
                this.columndescriptiondate1 = this.Columns["descriptiondate1"];
                this.columndescriptiondate2 = this.Columns["descriptiondate2"];
                this.columndescriptiondate3 = this.Columns["descriptiondate3"];
                this.columndescriptiondate4 = this.Columns["descriptiondate4"];
                this.columndescriptiondate5 = this.Columns["descriptiondate5"];
                this.columndescriptiondate6 = this.Columns["descriptiondate6"];
                this.columndescriptiondate7 = this.Columns["descriptiondate7"];
                this.columndescriptiondate8 = this.Columns["descriptiondate8"];
                this.columndescriptiondate9 = this.Columns["descriptiondate9"];
                this.columndescriptionint1 = this.Columns["descriptionint1"];
                this.columndescriptionint2 = this.Columns["descriptionint2"];
                this.columndescriptionint3 = this.Columns["descriptionint3"];
                this.columndescriptionint4 = this.Columns["descriptionint4"];
                this.columndescriptionint5 = this.Columns["descriptionint5"];
                this.columndescriptionint6 = this.Columns["descriptionint6"];
                this.columndescriptionint7 = this.Columns["descriptionint7"];
                this.columndescriptionint8 = this.Columns["descriptionint8"];
                this.columndescriptionint9 = this.Columns["descriptionint9"];
                this.columndescriptionfloat1 = this.Columns["descriptionfloat1"];
                this.columndescriptionfloat2 = this.Columns["descriptionfloat2"];
                this.columndescriptionfloat3 = this.Columns["descriptionfloat3"];
                this.columndescriptionfloat4 = this.Columns["descriptionfloat4"];
                this.columndescriptionfloat5 = this.Columns["descriptionfloat5"];
                this.columndescriptionfloat6 = this.Columns["descriptionfloat6"];
                this.columndescriptionfloat7 = this.Columns["descriptionfloat7"];
                this.columndescriptionfloat8 = this.Columns["descriptionfloat8"];
                this.columndescriptionfloat9 = this.Columns["descriptionfloat9"];
                this.columncu = this.Columns["cu"];
                this.columnct = this.Columns["ct"];
                this.columnlu = this.Columns["lu"];
                this.columnlt = this.Columns["lt"];
            }
            
            private void InitClass() {
                this.columnidinv = new DataColumn("idinv", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnidinv);
                this.columnnlevel = new DataColumn("nlevel", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnlevel);
                this.columnleveldescr = new DataColumn("leveldescr", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnleveldescr);
                this.columncodeinv = new DataColumn("codeinv", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncodeinv);
                this.columnparidinv = new DataColumn("paridinv", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnparidinv);
                this.columndescription = new DataColumn("description", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescription);
                this.columndescriptionstring1 = new DataColumn("descriptionstring1", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionstring1);
                this.columndescriptionstring2 = new DataColumn("descriptionstring2", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionstring2);
                this.columndescriptionstring3 = new DataColumn("descriptionstring3", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionstring3);
                this.columndescriptionstring4 = new DataColumn("descriptionstring4", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionstring4);
                this.columndescriptionstring5 = new DataColumn("descriptionstring5", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionstring5);
                this.columndescriptionstring6 = new DataColumn("descriptionstring6", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionstring6);
                this.columndescriptionstring7 = new DataColumn("descriptionstring7", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionstring7);
                this.columndescriptionstring8 = new DataColumn("descriptionstring8", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionstring8);
                this.columndescriptionstring9 = new DataColumn("descriptionstring9", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionstring9);
                this.columndescriptiondate1 = new DataColumn("descriptiondate1", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptiondate1);
                this.columndescriptiondate2 = new DataColumn("descriptiondate2", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptiondate2);
                this.columndescriptiondate3 = new DataColumn("descriptiondate3", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptiondate3);
                this.columndescriptiondate4 = new DataColumn("descriptiondate4", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptiondate4);
                this.columndescriptiondate5 = new DataColumn("descriptiondate5", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptiondate5);
                this.columndescriptiondate6 = new DataColumn("descriptiondate6", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptiondate6);
                this.columndescriptiondate7 = new DataColumn("descriptiondate7", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptiondate7);
                this.columndescriptiondate8 = new DataColumn("descriptiondate8", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptiondate8);
                this.columndescriptiondate9 = new DataColumn("descriptiondate9", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptiondate9);
                this.columndescriptionint1 = new DataColumn("descriptionint1", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionint1);
                this.columndescriptionint2 = new DataColumn("descriptionint2", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionint2);
                this.columndescriptionint3 = new DataColumn("descriptionint3", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionint3);
                this.columndescriptionint4 = new DataColumn("descriptionint4", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionint4);
                this.columndescriptionint5 = new DataColumn("descriptionint5", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionint5);
                this.columndescriptionint6 = new DataColumn("descriptionint6", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionint6);
                this.columndescriptionint7 = new DataColumn("descriptionint7", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionint7);
                this.columndescriptionint8 = new DataColumn("descriptionint8", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionint8);
                this.columndescriptionint9 = new DataColumn("descriptionint9", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionint9);
                this.columndescriptionfloat1 = new DataColumn("descriptionfloat1", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionfloat1);
                this.columndescriptionfloat2 = new DataColumn("descriptionfloat2", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionfloat2);
                this.columndescriptionfloat3 = new DataColumn("descriptionfloat3", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionfloat3);
                this.columndescriptionfloat4 = new DataColumn("descriptionfloat4", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionfloat4);
                this.columndescriptionfloat5 = new DataColumn("descriptionfloat5", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionfloat5);
                this.columndescriptionfloat6 = new DataColumn("descriptionfloat6", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionfloat6);
                this.columndescriptionfloat7 = new DataColumn("descriptionfloat7", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionfloat7);
                this.columndescriptionfloat8 = new DataColumn("descriptionfloat8", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionfloat8);
                this.columndescriptionfloat9 = new DataColumn("descriptionfloat9", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescriptionfloat9);
                this.columncu = new DataColumn("cu", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncu);
                this.columnct = new DataColumn("ct", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnct);
                this.columnlu = new DataColumn("lu", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnlu);
                this.columnlt = new DataColumn("lt", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnlt);
                this.Constraints.Add(new UniqueConstraint("vistaFormKey2", new DataColumn[] {
                                this.columnidinv}, true));
                this.columnidinv.AllowDBNull = false;
                this.columnidinv.Unique = true;
                this.columnnlevel.AllowDBNull = false;
                this.columnleveldescr.AllowDBNull = false;
                this.columncodeinv.AllowDBNull = false;
                this.columndescription.AllowDBNull = false;
                this.columncu.AllowDBNull = false;
                this.columnct.AllowDBNull = false;
                this.columnlu.AllowDBNull = false;
                this.columnlt.AllowDBNull = false;
            }
            
            public inventorytreeviewRow NewinventorytreeviewRow() {
                return ((inventorytreeviewRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new inventorytreeviewRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(inventorytreeviewRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.inventorytreeviewRowChanged != null)) {
                    this.inventorytreeviewRowChanged(this, new inventorytreeviewRowChangeEvent(((inventorytreeviewRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.inventorytreeviewRowChanging != null)) {
                    this.inventorytreeviewRowChanging(this, new inventorytreeviewRowChangeEvent(((inventorytreeviewRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.inventorytreeviewRowDeleted != null)) {
                    this.inventorytreeviewRowDeleted(this, new inventorytreeviewRowChangeEvent(((inventorytreeviewRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.inventorytreeviewRowDeleting != null)) {
                    this.inventorytreeviewRowDeleting(this, new inventorytreeviewRowChangeEvent(((inventorytreeviewRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveinventorytreeviewRow(inventorytreeviewRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class inventorytreeviewRow : DataRow {
            
            private inventorytreeviewDataTable tableinventorytreeview;
            
            internal inventorytreeviewRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableinventorytreeview = ((inventorytreeviewDataTable)(this.Table));
            }
            
            public string idinv {
                get {
                    return ((string)(this[this.tableinventorytreeview.idinvColumn]));
                }
                set {
                    this[this.tableinventorytreeview.idinvColumn] = value;
                }
            }
            
            public string nlevel {
                get {
                    return ((string)(this[this.tableinventorytreeview.nlevelColumn]));
                }
                set {
                    this[this.tableinventorytreeview.nlevelColumn] = value;
                }
            }
            
            public string leveldescr {
                get {
                    return ((string)(this[this.tableinventorytreeview.leveldescrColumn]));
                }
                set {
                    this[this.tableinventorytreeview.leveldescrColumn] = value;
                }
            }
            
            public string codeinv {
                get {
                    return ((string)(this[this.tableinventorytreeview.codeinvColumn]));
                }
                set {
                    this[this.tableinventorytreeview.codeinvColumn] = value;
                }
            }
            
            public string paridinv {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.paridinvColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.paridinvColumn] = value;
                }
            }
            
            public string description {
                get {
                    return ((string)(this[this.tableinventorytreeview.descriptionColumn]));
                }
                set {
                    this[this.tableinventorytreeview.descriptionColumn] = value;
                }
            }
            
            public string descriptionstring1 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionstring1Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionstring1Column] = value;
                }
            }
            
            public string descriptionstring2 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionstring2Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionstring2Column] = value;
                }
            }
            
            public string descriptionstring3 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionstring3Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionstring3Column] = value;
                }
            }
            
            public string descriptionstring4 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionstring4Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionstring4Column] = value;
                }
            }
            
            public string descriptionstring5 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionstring5Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionstring5Column] = value;
                }
            }
            
            public string descriptionstring6 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionstring6Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionstring6Column] = value;
                }
            }
            
            public string descriptionstring7 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionstring7Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionstring7Column] = value;
                }
            }
            
            public string descriptionstring8 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionstring8Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionstring8Column] = value;
                }
            }
            
            public string descriptionstring9 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionstring9Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionstring9Column] = value;
                }
            }
            
            public string descriptiondate1 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptiondate1Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptiondate1Column] = value;
                }
            }
            
            public string descriptiondate2 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptiondate2Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptiondate2Column] = value;
                }
            }
            
            public string descriptiondate3 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptiondate3Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptiondate3Column] = value;
                }
            }
            
            public string descriptiondate4 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptiondate4Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptiondate4Column] = value;
                }
            }
            
            public string descriptiondate5 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptiondate5Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptiondate5Column] = value;
                }
            }
            
            public string descriptiondate6 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptiondate6Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptiondate6Column] = value;
                }
            }
            
            public string descriptiondate7 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptiondate7Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptiondate7Column] = value;
                }
            }
            
            public string descriptiondate8 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptiondate8Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptiondate8Column] = value;
                }
            }
            
            public string descriptiondate9 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptiondate9Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptiondate9Column] = value;
                }
            }
            
            public string descriptionint1 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionint1Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionint1Column] = value;
                }
            }
            
            public string descriptionint2 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionint2Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionint2Column] = value;
                }
            }
            
            public string descriptionint3 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionint3Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionint3Column] = value;
                }
            }
            
            public string descriptionint4 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionint4Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionint4Column] = value;
                }
            }
            
            public string descriptionint5 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionint5Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionint5Column] = value;
                }
            }
            
            public string descriptionint6 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionint6Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionint6Column] = value;
                }
            }
            
            public string descriptionint7 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionint7Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionint7Column] = value;
                }
            }
            
            public string descriptionint8 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionint8Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionint8Column] = value;
                }
            }
            
            public string descriptionint9 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionint9Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionint9Column] = value;
                }
            }
            
            public string descriptionfloat1 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionfloat1Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionfloat1Column] = value;
                }
            }
            
            public string descriptionfloat2 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionfloat2Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionfloat2Column] = value;
                }
            }
            
            public string descriptionfloat3 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionfloat3Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionfloat3Column] = value;
                }
            }
            
            public string descriptionfloat4 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionfloat4Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionfloat4Column] = value;
                }
            }
            
            public string descriptionfloat5 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionfloat5Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionfloat5Column] = value;
                }
            }
            
            public string descriptionfloat6 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionfloat6Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionfloat6Column] = value;
                }
            }
            
            public string descriptionfloat7 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionfloat7Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionfloat7Column] = value;
                }
            }
            
            public string descriptionfloat8 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionfloat8Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionfloat8Column] = value;
                }
            }
            
            public string descriptionfloat9 {
                get {
                    try {
                        return ((string)(this[this.tableinventorytreeview.descriptionfloat9Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableinventorytreeview.descriptionfloat9Column] = value;
                }
            }
            
            public string cu {
                get {
                    return ((string)(this[this.tableinventorytreeview.cuColumn]));
                }
                set {
                    this[this.tableinventorytreeview.cuColumn] = value;
                }
            }
            
            public System.DateTime ct {
                get {
                    return ((System.DateTime)(this[this.tableinventorytreeview.ctColumn]));
                }
                set {
                    this[this.tableinventorytreeview.ctColumn] = value;
                }
            }
            
            public string lu {
                get {
                    return ((string)(this[this.tableinventorytreeview.luColumn]));
                }
                set {
                    this[this.tableinventorytreeview.luColumn] = value;
                }
            }
            
            public System.DateTime lt {
                get {
                    return ((System.DateTime)(this[this.tableinventorytreeview.ltColumn]));
                }
                set {
                    this[this.tableinventorytreeview.ltColumn] = value;
                }
            }
            
            public inventorytreeviewRow inventorytreeviewRowParent {
                get {
                    return ((inventorytreeviewRow)(this.GetParentRow(this.Table.ParentRelations["inventorytreeviewinventorytreeview"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["inventorytreeviewinventorytreeview"]);
                }
            }
            
            public inventorysortinglevelRow inventorysortinglevelRow {
                get {
                    return ((inventorysortinglevelRow)(this.GetParentRow(this.Table.ParentRelations["inventorysortinglevelinventorytreeview"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["inventorysortinglevelinventorytreeview"]);
                }
            }
            
            public bool IsparidinvNull() {
                return this.IsNull(this.tableinventorytreeview.paridinvColumn);
            }
            
            public void SetparidinvNull() {
                this[this.tableinventorytreeview.paridinvColumn] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionstring1Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionstring1Column);
            }
            
            public void Setdescriptionstring1Null() {
                this[this.tableinventorytreeview.descriptionstring1Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionstring2Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionstring2Column);
            }
            
            public void Setdescriptionstring2Null() {
                this[this.tableinventorytreeview.descriptionstring2Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionstring3Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionstring3Column);
            }
            
            public void Setdescriptionstring3Null() {
                this[this.tableinventorytreeview.descriptionstring3Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionstring4Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionstring4Column);
            }
            
            public void Setdescriptionstring4Null() {
                this[this.tableinventorytreeview.descriptionstring4Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionstring5Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionstring5Column);
            }
            
            public void Setdescriptionstring5Null() {
                this[this.tableinventorytreeview.descriptionstring5Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionstring6Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionstring6Column);
            }
            
            public void Setdescriptionstring6Null() {
                this[this.tableinventorytreeview.descriptionstring6Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionstring7Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionstring7Column);
            }
            
            public void Setdescriptionstring7Null() {
                this[this.tableinventorytreeview.descriptionstring7Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionstring8Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionstring8Column);
            }
            
            public void Setdescriptionstring8Null() {
                this[this.tableinventorytreeview.descriptionstring8Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionstring9Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionstring9Column);
            }
            
            public void Setdescriptionstring9Null() {
                this[this.tableinventorytreeview.descriptionstring9Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptiondate1Null() {
                return this.IsNull(this.tableinventorytreeview.descriptiondate1Column);
            }
            
            public void Setdescriptiondate1Null() {
                this[this.tableinventorytreeview.descriptiondate1Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptiondate2Null() {
                return this.IsNull(this.tableinventorytreeview.descriptiondate2Column);
            }
            
            public void Setdescriptiondate2Null() {
                this[this.tableinventorytreeview.descriptiondate2Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptiondate3Null() {
                return this.IsNull(this.tableinventorytreeview.descriptiondate3Column);
            }
            
            public void Setdescriptiondate3Null() {
                this[this.tableinventorytreeview.descriptiondate3Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptiondate4Null() {
                return this.IsNull(this.tableinventorytreeview.descriptiondate4Column);
            }
            
            public void Setdescriptiondate4Null() {
                this[this.tableinventorytreeview.descriptiondate4Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptiondate5Null() {
                return this.IsNull(this.tableinventorytreeview.descriptiondate5Column);
            }
            
            public void Setdescriptiondate5Null() {
                this[this.tableinventorytreeview.descriptiondate5Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptiondate6Null() {
                return this.IsNull(this.tableinventorytreeview.descriptiondate6Column);
            }
            
            public void Setdescriptiondate6Null() {
                this[this.tableinventorytreeview.descriptiondate6Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptiondate7Null() {
                return this.IsNull(this.tableinventorytreeview.descriptiondate7Column);
            }
            
            public void Setdescriptiondate7Null() {
                this[this.tableinventorytreeview.descriptiondate7Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptiondate8Null() {
                return this.IsNull(this.tableinventorytreeview.descriptiondate8Column);
            }
            
            public void Setdescriptiondate8Null() {
                this[this.tableinventorytreeview.descriptiondate8Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptiondate9Null() {
                return this.IsNull(this.tableinventorytreeview.descriptiondate9Column);
            }
            
            public void Setdescriptiondate9Null() {
                this[this.tableinventorytreeview.descriptiondate9Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionint1Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionint1Column);
            }
            
            public void Setdescriptionint1Null() {
                this[this.tableinventorytreeview.descriptionint1Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionint2Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionint2Column);
            }
            
            public void Setdescriptionint2Null() {
                this[this.tableinventorytreeview.descriptionint2Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionint3Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionint3Column);
            }
            
            public void Setdescriptionint3Null() {
                this[this.tableinventorytreeview.descriptionint3Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionint4Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionint4Column);
            }
            
            public void Setdescriptionint4Null() {
                this[this.tableinventorytreeview.descriptionint4Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionint5Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionint5Column);
            }
            
            public void Setdescriptionint5Null() {
                this[this.tableinventorytreeview.descriptionint5Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionint6Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionint6Column);
            }
            
            public void Setdescriptionint6Null() {
                this[this.tableinventorytreeview.descriptionint6Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionint7Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionint7Column);
            }
            
            public void Setdescriptionint7Null() {
                this[this.tableinventorytreeview.descriptionint7Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionint8Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionint8Column);
            }
            
            public void Setdescriptionint8Null() {
                this[this.tableinventorytreeview.descriptionint8Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionint9Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionint9Column);
            }
            
            public void Setdescriptionint9Null() {
                this[this.tableinventorytreeview.descriptionint9Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionfloat1Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionfloat1Column);
            }
            
            public void Setdescriptionfloat1Null() {
                this[this.tableinventorytreeview.descriptionfloat1Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionfloat2Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionfloat2Column);
            }
            
            public void Setdescriptionfloat2Null() {
                this[this.tableinventorytreeview.descriptionfloat2Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionfloat3Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionfloat3Column);
            }
            
            public void Setdescriptionfloat3Null() {
                this[this.tableinventorytreeview.descriptionfloat3Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionfloat4Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionfloat4Column);
            }
            
            public void Setdescriptionfloat4Null() {
                this[this.tableinventorytreeview.descriptionfloat4Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionfloat5Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionfloat5Column);
            }
            
            public void Setdescriptionfloat5Null() {
                this[this.tableinventorytreeview.descriptionfloat5Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionfloat6Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionfloat6Column);
            }
            
            public void Setdescriptionfloat6Null() {
                this[this.tableinventorytreeview.descriptionfloat6Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionfloat7Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionfloat7Column);
            }
            
            public void Setdescriptionfloat7Null() {
                this[this.tableinventorytreeview.descriptionfloat7Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionfloat8Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionfloat8Column);
            }
            
            public void Setdescriptionfloat8Null() {
                this[this.tableinventorytreeview.descriptionfloat8Column] = System.Convert.DBNull;
            }
            
            public bool Isdescriptionfloat9Null() {
                return this.IsNull(this.tableinventorytreeview.descriptionfloat9Column);
            }
            
            public void Setdescriptionfloat9Null() {
                this[this.tableinventorytreeview.descriptionfloat9Column] = System.Convert.DBNull;
            }
            
            public inventorytreeviewRow[] GetinventorytreeviewRows() {
                return ((inventorytreeviewRow[])(this.GetChildRows(this.Table.ChildRelations["inventorytreeviewinventorytreeview"])));
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class inventorytreeviewRowChangeEvent : EventArgs {
            
            private inventorytreeviewRow eventRow;
            
            private DataRowAction eventAction;
            
            public inventorytreeviewRowChangeEvent(inventorytreeviewRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public inventorytreeviewRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
