
/*
Easy
Copyright (C) 2022 Università degli Studi di Catania (www.unict.it)
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.854 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>serviceBancaIntesa</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>True</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace serviceBancaIntesa {
	using System;
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System.Collections;
	using System.Xml.Schema;
	using System.ComponentModel;
	using System.Collections.Generic;


	public partial class ct0000000002_pdpGeneraIUVResult {

		private ct0000000002_datiRestituiti datiRestituitiField;

		public ct0000000002_pdpGeneraIUVResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000002_pdpGeneraIUVResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000002_pdpGeneraIUVResult() {
			this.datiRestituitiField = new ct0000000002_datiRestituiti();
		}

		public ct0000000002_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000002_pdpGeneraIUVResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000002_pdpGeneraIUVResultCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,
	}

	public partial class ct0000000002_datiRestituiti {

		public string identificativoUnivocoVersamento { get; set; }

	}

	public partial class ct0000000003_pdpCaricaPagamentoInAttesa {

		private ct0000000003_datiPagamentoInAttesa datiPagamentoInAttesaField;

		public ct0000000003_pdpCaricaPagamentoInAttesaModalita modalita { get; set; }


		public ct0000000003_pdpCaricaPagamentoInAttesa() {
			this.datiPagamentoInAttesaField = new ct0000000003_datiPagamentoInAttesa();
		}

		public ct0000000003_datiPagamentoInAttesa datiPagamentoInAttesa {
			get {
				return this.datiPagamentoInAttesaField;
			}
			set {
				this.datiPagamentoInAttesaField = value;
			}
		}
	}

	public enum ct0000000003_pdpCaricaPagamentoInAttesaModalita {

		/// <remarks/>
		INS,

		/// <remarks/>
		MOD,

		/// <remarks/>
		INV,

		/// <remarks/>
		ASP,
	}

	public partial class ct0000000003_datiPagamentoInAttesa {

		private ct0000000003_notificaCallback notificaCallbackField;

		private ct0000000003_soggettoPagatore soggettoPagatoreField;

		private List<ct0000000003_datiSingoloVersamento> datiSingoloVersamentoField;

		public System.DateTime dataScadenzaPagamento { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool dataScadenzaPagamentoSpecified { get; set; }

		public string identificativoUnivocoVersamento { get; set; }

		public string id_tenant { get; set; }

		public decimal importoTotaleDaVersare { get; set; }

		public string causaleVersamentoEsplicitaPSP { get; set; }


		public ct0000000003_datiPagamentoInAttesa() {
			this.datiSingoloVersamentoField = new List<ct0000000003_datiSingoloVersamento>();
			this.soggettoPagatoreField = new ct0000000003_soggettoPagatore();
			this.notificaCallbackField = new ct0000000003_notificaCallback();
		}

		public ct0000000003_notificaCallback notificaCallback {
			get {
				return this.notificaCallbackField;
			}
			set {
				this.notificaCallbackField = value;
			}
		}

		public ct0000000003_soggettoPagatore soggettoPagatore {
			get {
				return this.soggettoPagatoreField;
			}
			set {
				this.soggettoPagatoreField = value;
			}
		}

		public List<ct0000000003_datiSingoloVersamento> datiSingoloVersamento {
			get {
				return this.datiSingoloVersamentoField;
			}
			set {
				this.datiSingoloVersamentoField = value;
			}
		}
	}

	public partial class ct0000000003_notificaCallback {

		public string callbackURL { get; set; }

		public string callbackUsername { get; set; }

		public string callbackPassword { get; set; }

	}

	public partial class ct0000000003_soggettoPagatore {

		public ct0000000003_soggettoPagatoreTipoIdentificativoUnivocoPagatore tipoIdentificativoUnivocoPagatore { get; set; }

		public string codiceIdentificativoUnivocoPagatore { get; set; }

		public string anagraficaPagatore { get; set; }

		public string indirizzoPagatore { get; set; }

		public string civicoPagatore { get; set; }

		public string capPagatore { get; set; }

		public string localitaPagatore { get; set; }

		public string provinciaPagatore { get; set; }

		public string nazionePagatore { get; set; }

		public string emailPagatore { get; set; }

	}

	public enum ct0000000003_soggettoPagatoreTipoIdentificativoUnivocoPagatore {

		/// <remarks/>
		F,

		/// <remarks/>
		G,
	}

	public partial class ct0000000003_datiSingoloVersamento {

		private ct0000000003_datiMarcaBolloDigitale datiMarcaBolloDigitaleField;

		public string identificativoServizio { get; set; }

		public decimal importoSingoloVersamento { get; set; }

		public string credenzialiPagatore { get; set; }

		public string descrizioneTestualeCausaleVersamento { get; set; }


		public ct0000000003_datiSingoloVersamento() {
			this.datiMarcaBolloDigitaleField = new ct0000000003_datiMarcaBolloDigitale();
		}

		public ct0000000003_datiMarcaBolloDigitale datiMarcaBolloDigitale {
			get {
				return this.datiMarcaBolloDigitaleField;
			}
			set {
				this.datiMarcaBolloDigitaleField = value;
			}
		}
	}

	public partial class ct0000000003_datiMarcaBolloDigitale {

		public string hashDocumento { get; set; }

		public string provinciaResidenzaPagatore { get; set; }

	}

	public partial class ct0000000004_pdpCaricaPagamentoInAttesaResult {

		private ct0000000004_datiRestituiti datiRestituitiField;

		public ct0000000004_pdpCaricaPagamentoInAttesaResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000004_pdpCaricaPagamentoInAttesaResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000004_pdpCaricaPagamentoInAttesaResult() {
			this.datiRestituitiField = new ct0000000004_datiRestituiti();
		}

		public ct0000000004_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000004_pdpCaricaPagamentoInAttesaResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000004_pdpCaricaPagamentoInAttesaResultCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		WS_IDENTIFICATIVO_ASSENTE,

		/// <remarks/>
		WS_IUV_NON_TROVATO,

		/// <remarks/>
		WS_MODALITA_SCONOSCIUTA,

		/// <remarks/>
		WS_IUV_GIA_PRESENTE,

		/// <remarks/>
		WS_PAGAMENTO_IN_CORSO,

		/// <remarks/>
		WS_SERVIZIO_NON_AUTORIZZATO,
	}

	public partial class ct0000000004_datiRestituiti {

		public string identificativoUnivocoVersamento { get; set; }

		public string idTenant { get; set; }

	}

	public partial class ct0000000005_pdpCancellaPagamentoInAttesa {

		public string identificativoUnivocoVersamento { get; set; }

	}

	public partial class ct0000000006_pdpCancellaPagamentoInAttesaResult {

		public ct0000000006_pdpCancellaPagamentoInAttesaResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000006_pdpCancellaPagamentoInAttesaResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }

	}

	public enum ct0000000006_pdpCancellaPagamentoInAttesaResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000006_pdpCancellaPagamentoInAttesaResultCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_PAGAMENTO_IN_CORSO,

		/// <remarks/>
		WS_ERRORE_INTERNO,
	}

	public partial class ct0000000007_pdpGeneraRPT {

		private ct0000000007_parametriPSP parametriPSPField;

		private ct0000000007_datiPagamentoInAttesa datiPagamentoInAttesaField;

		public string identificativoStazioneRichiedente { get; set; }

		public ct0000000007_pdpGeneraRPTTipoVersamento tipoVersamento { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool tipoVersamentoSpecified { get; set; }


		public ct0000000007_pdpGeneraRPT() {
			this.datiPagamentoInAttesaField = new ct0000000007_datiPagamentoInAttesa();
			this.parametriPSPField = new ct0000000007_parametriPSP();
		}

		public ct0000000007_parametriPSP parametriPSP {
			get {
				return this.parametriPSPField;
			}
			set {
				this.parametriPSPField = value;
			}
		}

		public ct0000000007_datiPagamentoInAttesa datiPagamentoInAttesa {
			get {
				return this.datiPagamentoInAttesaField;
			}
			set {
				this.datiPagamentoInAttesaField = value;
			}
		}
	}

	public enum ct0000000007_pdpGeneraRPTTipoVersamento {

		/// <remarks/>
		BBT,

		/// <remarks/>
		BP,

		/// <remarks/>
		AD,

		/// <remarks/>
		CP,

		/// <remarks/>
		PO,

		/// <remarks/>
		OBEP,
	}

	public partial class ct0000000007_parametriPSP {

		public string identificativoPSP { get; set; }

		public string identificativoIntermediarioPSP { get; set; }

		public string identificativoCanale { get; set; }

	}

	public partial class ct0000000007_datiPagamentoInAttesa {

		private ct0000000007_notificaCallback notificaCallbackField;

		private ct0000000007_soggettoPagatore soggettoPagatoreField;

		private ct0000000007_soggettoVersante soggettoVersanteField;

		private List<ct0000000007_datiSingoloVersamento> datiSingoloVersamentoField;

		public System.DateTime dataScadenzaPagamento { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool dataScadenzaPagamentoSpecified { get; set; }

		public string identificativoUnivocoVersamento { get; set; }

		public string codiceContestoPagamento { get; set; }

		public string ibanAddebito { get; set; }

		public string bicAddebito { get; set; }

		public decimal importoTotaleDaVersare { get; set; }

		public ct0000000007_datiPagamentoInAttesaAutenticazioneSoggetto autenticazioneSoggetto { get; set; }


		public ct0000000007_datiPagamentoInAttesa() {
			this.datiSingoloVersamentoField = new List<ct0000000007_datiSingoloVersamento>();
			this.soggettoVersanteField = new ct0000000007_soggettoVersante();
			this.soggettoPagatoreField = new ct0000000007_soggettoPagatore();
			this.notificaCallbackField = new ct0000000007_notificaCallback();
		}

		public ct0000000007_notificaCallback notificaCallback {
			get {
				return this.notificaCallbackField;
			}
			set {
				this.notificaCallbackField = value;
			}
		}

		public ct0000000007_soggettoPagatore soggettoPagatore {
			get {
				return this.soggettoPagatoreField;
			}
			set {
				this.soggettoPagatoreField = value;
			}
		}

		public ct0000000007_soggettoVersante soggettoVersante {
			get {
				return this.soggettoVersanteField;
			}
			set {
				this.soggettoVersanteField = value;
			}
		}

		public List<ct0000000007_datiSingoloVersamento> datiSingoloVersamento {
			get {
				return this.datiSingoloVersamentoField;
			}
			set {
				this.datiSingoloVersamentoField = value;
			}
		}
	}

	public partial class ct0000000007_notificaCallback {

		public string callbackURL { get; set; }

		public string callbackUsername { get; set; }

		public string callbackPassword { get; set; }

	}

	public partial class ct0000000007_soggettoPagatore {

		public ct0000000007_soggettoPagatoreTipoIdentificativoUnivocoPagatore tipoIdentificativoUnivocoPagatore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool tipoIdentificativoUnivocoPagatoreSpecified { get; set; }

		public string codiceIdentificativoUnivocoPagatore { get; set; }

		public string anagraficaPagatore { get; set; }

		public string indirizzoPagatore { get; set; }

		public string civicoPagatore { get; set; }

		public string capPagatore { get; set; }

		public string localitaPagatore { get; set; }

		public string provinciaPagatore { get; set; }

		public string nazionePagatore { get; set; }

		public string emailPagatore { get; set; }

	}

	public enum ct0000000007_soggettoPagatoreTipoIdentificativoUnivocoPagatore {

		/// <remarks/>
		F,

		/// <remarks/>
		G,
	}

	public enum ct0000000007_datiPagamentoInAttesaAutenticazioneSoggetto {

		/// <remarks/>
		CNS,

		/// <remarks/>
		USR,

		/// <remarks/>
		OTH,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("N/A")]
		NA,
	}

	public partial class ct0000000007_soggettoVersante {

		public ct0000000007_soggettoVersanteTipoIdentificativoUnivocoVersante tipoIdentificativoUnivocoVersante { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool tipoIdentificativoUnivocoVersanteSpecified { get; set; }

		public string codiceIdentificativoUnivocoVersante { get; set; }

		public string anagraficaVersante { get; set; }

		public string indirizzoVersante { get; set; }

		public string civicoVersante { get; set; }

		public string capVersante { get; set; }

		public string localitaVersante { get; set; }

		public string provinciaVersante { get; set; }

		public string nazioneVersante { get; set; }

		public string emailVersante { get; set; }

	}

	public enum ct0000000007_soggettoVersanteTipoIdentificativoUnivocoVersante {

		/// <remarks/>
		F,

		/// <remarks/>
		G,
	}

	public partial class ct0000000007_datiSingoloVersamento {

		private ct0000000007_datiMarcaBolloDigitale datiMarcaBolloDigitaleField;

		public string identificativoServizio { get; set; }

		public decimal importoSingoloVersamento { get; set; }

		public decimal commissioneCaricoPA { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool commissioneCaricoPASpecified { get; set; }

		public string credenzialiPagatore { get; set; }

		public string descrizioneTestualeCausaleVersamento { get; set; }

		public string causaleVersamentoEsplicitaPSP { get; set; }


		public ct0000000007_datiSingoloVersamento() {
			this.datiMarcaBolloDigitaleField = new ct0000000007_datiMarcaBolloDigitale();
		}

		public ct0000000007_datiMarcaBolloDigitale datiMarcaBolloDigitale {
			get {
				return this.datiMarcaBolloDigitaleField;
			}
			set {
				this.datiMarcaBolloDigitaleField = value;
			}
		}
	}

	public partial class ct0000000007_datiMarcaBolloDigitale {

		public string hashDocumento { get; set; }

		public string provinciaResidenzaPagatore { get; set; }

	}

	public partial class ct0000000008_pdpGeneraRPTResult {

		private ct0000000008_datiRestituiti datiRestituitiField;

		public ct0000000008_pdpGeneraRPTResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000008_pdpGeneraRPTResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000008_pdpGeneraRPTResult() {
			this.datiRestituitiField = new ct0000000008_datiRestituiti();
		}

		public ct0000000008_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000008_pdpGeneraRPTResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000008_pdpGeneraRPTResultCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		PDP_PIAIUV_ERRORE_COMPETENZA_DATI,

		/// <remarks/>
		PDP_PIA_ERRORE_FORMATO_DATI,

		/// <remarks/>
		PDP_PIA_GIA_INSERITO,

		/// <remarks/>
		PDP_PIASV_ERRORE_FORMATO_DATI,

		/// <remarks/>
		PDP_PIAIUV_DA_MODIFICARE_NON_INDICATO,

		/// <remarks/>
		PDP_PIAIUV_DA_INSERIRE_GIA_ESISTE,

		/// <remarks/>
		PDP_PIAIUV_DA_MODIFICARE_NON_TROVATO,

		/// <remarks/>
		PDP_PIAIUV_NON_MODIFICABILE,

		/// <remarks/>
		PDP_PIASV_SERVIZIO_NON_VALIDO,

		/// <remarks/>
		PDP_PIASV_ERRORE_QUADRATURA_IMPORTI,

		/// <remarks/>
		PDP_RPT_ERRORE_IBAN_ADDEBITO,

		/// <remarks/>
		PDP_RPT_TIPO_VERS_OBEP_NON_APPLICABILE,

		/// <remarks/>
		PDP_PSP_CANALE_NON_VALIDO,

		/// <remarks/>
		PDP_RPT_NON_SODDISFA_SANP,

		/// <remarks/>
		PDP_ERRORE_NAMESPACE_NON_CORRETTO,

		/// <remarks/>
		PDP_GEN_ERRORE_SINTASSI,

		/// <remarks/>
		PDP_GEN_ACCESSO_NON_AUTORIZZATO,

		/// <remarks/>
		PDP_GEN_BU_NON_TROVATA,

		/// <remarks/>
		PDP_GEN_DECODIFICA_PARAM,

		/// <remarks/>
		PDP_GEN_RICHIESTA_NON_SUPPORTATA,

		/// <remarks/>
		PDP_ERRORE_INTERNO_XSD,

		/// <remarks/>
		PDP_LINEA_ERRORE_SINTASSI,

		/// <remarks/>
		PDP_ERRORE_RITORNO_XSD,

		/// <remarks/>
		PDP_ERRORE_INTERNO,
	}

	public partial class ct0000000008_datiRestituiti {

		public string identificativoUnivocoVersamento { get; set; }

		public string pspSupportaRedirect { get; set; }

		public string redirectURL { get; set; }

	}

	public partial class ct0000000009_pdpInviaRPT {

		private ct0000000009_parametriPSP parametriPSPField;

		private ct0000000009_datiPagamentoInAttesa datiPagamentoInAttesaField;

		public string identificativoUnivocoVersamento { get; set; }

		public string identificativoStazioneRichiedente { get; set; }

		public ct0000000009_pdpInviaRPTTipoVersamento tipoVersamento { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool tipoVersamentoSpecified { get; set; }


		public ct0000000009_pdpInviaRPT() {
			this.datiPagamentoInAttesaField = new ct0000000009_datiPagamentoInAttesa();
			this.parametriPSPField = new ct0000000009_parametriPSP();
		}

		public ct0000000009_parametriPSP parametriPSP {
			get {
				return this.parametriPSPField;
			}
			set {
				this.parametriPSPField = value;
			}
		}

		public ct0000000009_datiPagamentoInAttesa datiPagamentoInAttesa {
			get {
				return this.datiPagamentoInAttesaField;
			}
			set {
				this.datiPagamentoInAttesaField = value;
			}
		}
	}

	public enum ct0000000009_pdpInviaRPTTipoVersamento {

		/// <remarks/>
		BBT,

		/// <remarks/>
		BP,

		/// <remarks/>
		AD,

		/// <remarks/>
		CP,

		/// <remarks/>
		PO,

		/// <remarks/>
		OBEP,
	}

	public partial class ct0000000009_parametriPSP {

		public string identificativoPSP { get; set; }

		public string identificativoIntermediarioPSP { get; set; }

		public string identificativoCanale { get; set; }

	}

	public partial class ct0000000009_datiPagamentoInAttesa {

		private ct0000000009_notificaCallback notificaCallbackField;

		private ct0000000009_soggettoVersante soggettoVersanteField;

		private List<ct0000000009_datiSingoloVersamento> datiSingoloVersamentoField;

		public ct0000000009_datiPagamentoInAttesaAutenticazioneSoggetto autenticazioneSoggetto { get; set; }

		public string codiceContestoPagamento { get; set; }

		public string ibanAddebito { get; set; }

		public string bicAddebito { get; set; }


		public ct0000000009_datiPagamentoInAttesa() {
			this.datiSingoloVersamentoField = new List<ct0000000009_datiSingoloVersamento>();
			this.soggettoVersanteField = new ct0000000009_soggettoVersante();
			this.notificaCallbackField = new ct0000000009_notificaCallback();
		}

		public ct0000000009_notificaCallback notificaCallback {
			get {
				return this.notificaCallbackField;
			}
			set {
				this.notificaCallbackField = value;
			}
		}

		public ct0000000009_soggettoVersante soggettoVersante {
			get {
				return this.soggettoVersanteField;
			}
			set {
				this.soggettoVersanteField = value;
			}
		}

		public List<ct0000000009_datiSingoloVersamento> datiSingoloVersamento {
			get {
				return this.datiSingoloVersamentoField;
			}
			set {
				this.datiSingoloVersamentoField = value;
			}
		}
	}

	public enum ct0000000009_datiPagamentoInAttesaAutenticazioneSoggetto {

		/// <remarks/>
		CNS,

		/// <remarks/>
		USR,

		/// <remarks/>
		OTH,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("N/A")]
		NA,
	}

	public partial class ct0000000009_notificaCallback {

		public string callbackURL { get; set; }

		public string callbackUsername { get; set; }

		public string callbackPassword { get; set; }

	}

	public partial class ct0000000009_soggettoVersante {

		public ct0000000009_soggettoVersanteTipoIdentificativoUnivocoVersante tipoIdentificativoUnivocoVersante { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool tipoIdentificativoUnivocoVersanteSpecified { get; set; }

		public string codiceIdentificativoUnivocoVersante { get; set; }

		public string anagraficaVersante { get; set; }

		public string indirizzoVersante { get; set; }

		public string civicoVersante { get; set; }

		public string capVersante { get; set; }

		public string localitaVersante { get; set; }

		public string provinciaVersante { get; set; }

		public string nazioneVersante { get; set; }

		public string emailVersante { get; set; }

	}

	public enum ct0000000009_soggettoVersanteTipoIdentificativoUnivocoVersante {

		/// <remarks/>
		F,

		/// <remarks/>
		G,
	}

	public partial class ct0000000009_datiSingoloVersamento {

		public decimal commissioneCaricoPA { get; set; }

	}

	public partial class ct0000000010_pdpInviaRPTResult {

		private ct0000000010_datiRestituiti datiRestituitiField;

		public ct0000000010_pdpInviaRPTResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000010_pdpInviaRPTResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000010_pdpInviaRPTResult() {
			this.datiRestituitiField = new ct0000000010_datiRestituiti();
		}

		public ct0000000010_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000010_pdpInviaRPTResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000010_pdpInviaRPTResultCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		PDP_PIAIUV_ERRORE_COMPETENZA_DATI,

		/// <remarks/>
		PDP_RPT_PIA_ANNULLATO,

		/// <remarks/>
		PDP_RPT_PIA_GIA_USATO,

		/// <remarks/>
		PDP_RPT_PIA_GIA_PAGATO,

		/// <remarks/>
		PDP_RPT_PIA_SCADUTO,

		/// <remarks/>
		PDP_RPT_IUV_NON_TROVATO,

		/// <remarks/>
		PDP_RPT_IUV_NON_ASSOCIATO_A_PIA,

		/// <remarks/>
		PDP_RPT_PSP_O_CCP_NON_ACCETTATI,

		/// <remarks/>
		PDP_RPT_IUV_GIA_USATO,

		/// <remarks/>
		PDP_RPT_ERRORE_IBAN_ADDEBITO,

		/// <remarks/>
		PDP_RPT_TIPO_VERS_OBEP_NON_APPLICABILE,

		/// <remarks/>
		PDP_PSP_CANALE_NON_VALIDO,

		/// <remarks/>
		PDP_RPT_PAGAMENTO,

		/// <remarks/>
		PDP_RPT_NON_SODDISFA_SANP,

		/// <remarks/>
		PDP_ERRORE_NAMESPACE_NON_CORRETTO,

		/// <remarks/>
		PDP_GEN_ERRORE_SINTASSI,

		/// <remarks/>
		PDP_GEN_ACCESSO_NON_AUTORIZZATO,

		/// <remarks/>
		PDP_GEN_BU_NON_TROVATA,

		/// <remarks/>
		PDP_GEN_DECODIFICA_PARAM,

		/// <remarks/>
		PDP_GEN_RICHIESTA_NON_SUPPORTATA,

		/// <remarks/>
		PDP_ERRORE_INTERNO_XSD,

		/// <remarks/>
		PDP_LINEA_ERRORE_SINTASSI,

		/// <remarks/>
		PDP_ERRORE_RITORNO_XSD,

		/// <remarks/>
		PDP_ERRORE_INTERNO,
	}

	public partial class ct0000000010_datiRestituiti {

		public string pspSupportaRedirect { get; set; }

		public string redirectURL { get; set; }

	}

	public partial class ct0000000011_pdpChiediStatoRPT {

		public string identificativoUnivocoVersamento { get; set; }

		public string codiceContestoPagamento { get; set; }

	}

	public partial class ct0000000012_pdpChiediStatoRPTResult {

		private ct0000000012_datiRestituiti datiRestituitiField;

		public ct0000000012_pdpChiediStatoRPTResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000012_pdpChiediStatoRPTResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000012_pdpChiediStatoRPTResult() {
			this.datiRestituitiField = new ct0000000012_datiRestituiti();
		}

		public ct0000000012_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000012_pdpChiediStatoRPTResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000012_pdpChiediStatoRPTResultCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		WS_IUV_NON_TROVATO,

		/// <remarks/>
		PPT_RPT_SCONOSCIUTA,

		/// <remarks/>
		PPT_SINTASSI_EXTRAXSD,

		/// <remarks/>
		PPT_SEMANTICA,

		/// <remarks/>
		PPT_AUTENTICAZIONE,

		/// <remarks/>
		PPT_AUTORIZZAZIONE,

		/// <remarks/>
		PPT_DOMINIO_SCONOSCIUTO,

		/// <remarks/>
		PPT_DOMINIO_DISABILITATO,

		/// <remarks/>
		PPT_INTERMEDIARIO_PA_SCONOSCIUTO,

		/// <remarks/>
		PPT_INTERMEDIARIO_PA_DISABILITATO,

		/// <remarks/>
		PPT_STAZIONE_INT_PA_SCONOSCIUTA,

		/// <remarks/>
		PPT_STAZIONE_INT_PA_DISABILITATA,

		/// <remarks/>
		PPT_SUPERAMENTOSOGLIA,
	}

	public partial class ct0000000012_datiRestituiti {

		private List<ct0000000012_tipoElementoListaStorico> storicoListaField;

		public ct0000000012_datiRestituitiStato stato { get; set; }


		public ct0000000012_datiRestituiti() {
			this.storicoListaField = new List<ct0000000012_tipoElementoListaStorico>();
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("elementoListaStorico", IsNullable = false)]
		public List<ct0000000012_tipoElementoListaStorico> storicoLista {
			get {
				return this.storicoListaField;
			}
			set {
				this.storicoListaField = value;
			}
		}
	}

	public enum ct0000000012_datiRestituitiStato {

		/// <remarks/>
		RPT_RICEVUTA_NODO,

		/// <remarks/>
		RPT_RIFIUTATA_NODO,

		/// <remarks/>
		RPT_ACCETTATA_NODO,

		/// <remarks/>
		RPT_RIFIUTATA_PSP,

		/// <remarks/>
		RPT_ERRORE_INVIO_A_PSP,

		/// <remarks/>
		RPT_INVIATA_A_PSP,

		/// <remarks/>
		RPT_ACCETTATA_PSP,

		/// <remarks/>
		RPT_DECORSI_TERMINI,

		/// <remarks/>
		RT_RICEVUTA_NODO,

		/// <remarks/>
		RT_RIFIUTATA_NODO,

		/// <remarks/>
		RT_ACCETTATA_NODO,

		/// <remarks/>
		RT_ACCETTATA_PA,

		/// <remarks/>
		RT_RIFIUTATA_PA,

		/// <remarks/>
		RT_ESITO_SCONOSCIUTO_PA,
	}

	public partial class ct0000000012_tipoElementoListaStorico {

		public System.DateTime data { get; set; }

		public string stato { get; set; }

		public string descrizione { get; set; }

	}

	public partial class ct0000000013_pdpRecuperaRPT {

		public string identificativoUnivocoVersamento { get; set; }

		public string codiceContestoPagamento { get; set; }

	}

	public partial class ct0000000014_pdpRecuperaRPTResult {

		private ct0000000014_datiRestituiti datiRestituitiField;

		public ct0000000014_pdpRecuperaRPTResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000014_pdpRecuperaRPTResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000014_pdpRecuperaRPTResult() {
			this.datiRestituitiField = new ct0000000014_datiRestituiti();
		}

		public ct0000000014_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000014_pdpRecuperaRPTResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000014_pdpRecuperaRPTResultCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		PDP_PIAIUV_ERRORE_COMPETENZA_DATI,

		/// <remarks/>
		PDP_RPT_NON_TROVATA,
	}

	public partial class ct0000000014_datiRestituiti {

		private ct0000000014_parametriPSP parametriPSPField;

		private ct0000000014_soggettoVersante soggettoVersanteField;

		private ct0000000014_soggettoPagatore soggettoPagatoreField;

		private ct0000000014_enteBeneficiario enteBeneficiarioField;

		private ct0000000014_datiVersamento datiVersamentoField;

		public string identificativoStazioneRichiedente { get; set; }

		public string identificativoMessaggioRichiesta { get; set; }

		public System.DateTime dataOraMessaggioRichiesta { get; set; }

		public ct0000000014_datiRestituitiAutenticazioneSoggetto autenticazioneSoggetto { get; set; }


		public ct0000000014_datiRestituiti() {
			this.datiVersamentoField = new ct0000000014_datiVersamento();
			this.enteBeneficiarioField = new ct0000000014_enteBeneficiario();
			this.soggettoPagatoreField = new ct0000000014_soggettoPagatore();
			this.soggettoVersanteField = new ct0000000014_soggettoVersante();
			this.parametriPSPField = new ct0000000014_parametriPSP();
		}

		public ct0000000014_parametriPSP parametriPSP {
			get {
				return this.parametriPSPField;
			}
			set {
				this.parametriPSPField = value;
			}
		}

		public ct0000000014_soggettoVersante soggettoVersante {
			get {
				return this.soggettoVersanteField;
			}
			set {
				this.soggettoVersanteField = value;
			}
		}

		public ct0000000014_soggettoPagatore soggettoPagatore {
			get {
				return this.soggettoPagatoreField;
			}
			set {
				this.soggettoPagatoreField = value;
			}
		}

		public ct0000000014_enteBeneficiario enteBeneficiario {
			get {
				return this.enteBeneficiarioField;
			}
			set {
				this.enteBeneficiarioField = value;
			}
		}

		public ct0000000014_datiVersamento datiVersamento {
			get {
				return this.datiVersamentoField;
			}
			set {
				this.datiVersamentoField = value;
			}
		}
	}

	public partial class ct0000000014_parametriPSP {

		public string identificativoPSP { get; set; }

		public string identificativoIntermediarioPSP { get; set; }

		public string identificativoCanale { get; set; }

	}

	public enum ct0000000014_datiRestituitiAutenticazioneSoggetto {

		/// <remarks/>
		CNS,

		/// <remarks/>
		USR,

		/// <remarks/>
		OTH,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("N/A")]
		NA,
	}

	public partial class ct0000000014_soggettoVersante {

		public ct0000000014_soggettoVersanteTipoIdentificativoUnivocoVersante tipoIdentificativoUnivocoVersante { get; set; }

		public string codiceIdentificativoUnivocoVersante { get; set; }

		public string anagraficaVersante { get; set; }

		public string indirizzoVersante { get; set; }

		public string civicoVersante { get; set; }

		public string capVersante { get; set; }

		public string localitaVersante { get; set; }

		public string provinciaVersante { get; set; }

		public string nazioneVersante { get; set; }

		public string emailVersante { get; set; }

	}

	public enum ct0000000014_soggettoVersanteTipoIdentificativoUnivocoVersante {

		/// <remarks/>
		F,

		/// <remarks/>
		G,
	}

	public partial class ct0000000014_soggettoPagatore {

		public ct0000000014_soggettoPagatoreTipoIdentificativoUnivocoPagatore tipoIdentificativoUnivocoPagatore { get; set; }

		public string codiceIdentificativoUnivocoPagatore { get; set; }

		public string anagraficaPagatore { get; set; }

		public string indirizzoPagatore { get; set; }

		public string civicoPagatore { get; set; }

		public string capPagatore { get; set; }

		public string localitaPagatore { get; set; }

		public string provinciaPagatore { get; set; }

		public string nazionePagatore { get; set; }

		public string emailPagatore { get; set; }

	}

	public enum ct0000000014_soggettoPagatoreTipoIdentificativoUnivocoPagatore {

		/// <remarks/>
		F,

		/// <remarks/>
		G,
	}

	public partial class ct0000000014_enteBeneficiario {

		public ct0000000014_enteBeneficiarioTipoIdentificativoUnivocoBeneficiario tipoIdentificativoUnivocoBeneficiario { get; set; }

		public string codiceIdentificativoUnivocoBeneficiario { get; set; }

		public string denominazioneBeneficiario { get; set; }

		public string codiceUnitOperBeneficiario { get; set; }

		public string denomUnitOperBeneficiario { get; set; }

		public string indirizzoBeneficiario { get; set; }

		public string civicoBeneficiario { get; set; }

		public string capBeneficiario { get; set; }

		public string localitaBeneficiario { get; set; }

		public string provinciaBeneficiario { get; set; }

		public string nazioneBeneficiario { get; set; }

	}

	public enum ct0000000014_enteBeneficiarioTipoIdentificativoUnivocoBeneficiario {

		/// <remarks/>
		G,
	}

	public partial class ct0000000014_datiVersamento {

		private List<ct0000000014_datiSingoloVersamento> datiSingoloVersamentoField;

		public System.DateTime dataEsecuzionePagamento { get; set; }

		public decimal importoTotaleDaVersare { get; set; }

		public ct0000000014_datiVersamentoTipoVersamento tipoVersamento { get; set; }

		public string identificativoUnivocoVersamento { get; set; }

		public string codiceContestoPagamento { get; set; }

		public string ibanAddebito { get; set; }

		public string bicAddebito { get; set; }

		public ct0000000014_datiVersamentoFirmaRicevuta firmaRicevuta { get; set; }


		public ct0000000014_datiVersamento() {
			this.datiSingoloVersamentoField = new List<ct0000000014_datiSingoloVersamento>();
		}

		public List<ct0000000014_datiSingoloVersamento> datiSingoloVersamento {
			get {
				return this.datiSingoloVersamentoField;
			}
			set {
				this.datiSingoloVersamentoField = value;
			}
		}
	}

	public enum ct0000000014_datiVersamentoTipoVersamento {

		/// <remarks/>
		BBT,

		/// <remarks/>
		BP,

		/// <remarks/>
		AD,

		/// <remarks/>
		CP,

		/// <remarks/>
		PO,

		/// <remarks/>
		OBEP,
	}

	public enum ct0000000014_datiVersamentoFirmaRicevuta {

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("0")]
		Item0,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1")]
		Item1,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3")]
		Item3,
	}

	public partial class ct0000000014_datiSingoloVersamento {

		private ct0000000014_datiMarcaBolloDigitale datiMarcaBolloDigitaleField;

		public string identificativoServizio { get; set; }

		public decimal importoSingoloVersamento { get; set; }

		public decimal commissioneCaricoPA { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool commissioneCaricoPASpecified { get; set; }

		public string ibanAccredito { get; set; }

		public string bicAccredito { get; set; }

		public string ibanAppoggio { get; set; }

		public string bicAppoggio { get; set; }

		public string credenzialiPagatore { get; set; }

		public string causaleVersamento { get; set; }

		public string descrizioneTestualeCausaleVersamento { get; set; }

		public string causaleVersamentoEsplicitaPSP { get; set; }

		public string datiSpecificiRiscossione { get; set; }


		public ct0000000014_datiSingoloVersamento() {
			this.datiMarcaBolloDigitaleField = new ct0000000014_datiMarcaBolloDigitale();
		}

		public ct0000000014_datiMarcaBolloDigitale datiMarcaBolloDigitale {
			get {
				return this.datiMarcaBolloDigitaleField;
			}
			set {
				this.datiMarcaBolloDigitaleField = value;
			}
		}
	}

	public partial class ct0000000014_datiMarcaBolloDigitale {

		public string tipoBollo { get; set; }

		public string hashDocumento { get; set; }

		public string provinciaResidenzaPagatore { get; set; }

	}

	public partial class ct0000000015_pdpRecuperaRT {

		public string identificativoUnivocoVersamento { get; set; }

		public string codiceContestoPagamento { get; set; }

	}

	public partial class ct0000000016_pdpRecuperaRTResult {

		private ct0000000016_datiRestituiti datiRestituitiField;

		public ct0000000016_pdpRecuperaRTResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000016_pdpRecuperaRTResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000016_pdpRecuperaRTResult() {
			this.datiRestituitiField = new ct0000000016_datiRestituiti();
		}

		public ct0000000016_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000016_pdpRecuperaRTResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000016_pdpRecuperaRTResultCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		PDP_RPT_RT_NON_TROVATA,

		/// <remarks/>
		PDP_ERRORE_NAMESPACE_NON_CORRETTO,

		/// <remarks/>
		PDP_GEN_ERRORE_SINTASSI,

		/// <remarks/>
		PDP_GEN_ACCESSO_NON_AUTORIZZATO,

		/// <remarks/>
		PDP_GEN_BU_NON_TROVATA,

		/// <remarks/>
		PDP_GEN_DECODIFICA_PARAM,

		/// <remarks/>
		PDP_GEN_RICHIESTA_NON_SUPPORTATA,

		/// <remarks/>
		PDP_ERRORE_INTERNO_XSD,

		/// <remarks/>
		PDP_LINEA_ERRORE_SINTASSI,

		/// <remarks/>
		PDP_ERRORE_RITORNO_XSD,

		/// <remarks/>
		PDP_ERRORE_INTERNO,
	}

	public partial class ct0000000016_datiRestituiti {

		private ct0000000016_parametriPSP parametriPSPField;

		private ct0000000016_datiPagamento datiPagamentoField;

		public string xmlRT { get; set; }

		public string pdfRT { get; set; }

		public string identificativoMessaggioRicevuta { get; set; }

		public ct0000000016_datiRestituitiCodiceEsitoPagamento codiceEsitoPagamento { get; set; }

		public decimal importoTotalePagato { get; set; }

		public string identificativoUnivocoVersamento { get; set; }

		public string codiceContestoPagamento { get; set; }

		public System.DateTime dataCreazioneRicevuta { get; set; }


		public ct0000000016_datiRestituiti() {
			this.datiPagamentoField = new ct0000000016_datiPagamento();
			this.parametriPSPField = new ct0000000016_parametriPSP();
		}

		public ct0000000016_parametriPSP parametriPSP {
			get {
				return this.parametriPSPField;
			}
			set {
				this.parametriPSPField = value;
			}
		}

		public ct0000000016_datiPagamento datiPagamento {
			get {
				return this.datiPagamentoField;
			}
			set {
				this.datiPagamentoField = value;
			}
		}
	}

	public partial class ct0000000016_parametriPSP {

		public string identificativoPSP { get; set; }

		public string identificativoIntermediarioPSP { get; set; }

		public string identificativoCanale { get; set; }

	}

	public partial class ct0000000016_datiPagamento {

		private List<ct0000000016_datiSingoloPagamento> datiSingoloPagamentoField;

		public ct0000000016_datiPagamentoTipoVersamento tipoVersamento { get; set; }

		public string parametriAggiuntivi { get; set; }

		public string causaleVersamentoEsplicitaPSP { get; set; }


		public ct0000000016_datiPagamento() {
			this.datiSingoloPagamentoField = new List<ct0000000016_datiSingoloPagamento>();
		}

		public List<ct0000000016_datiSingoloPagamento> datiSingoloPagamento {
			get {
				return this.datiSingoloPagamentoField;
			}
			set {
				this.datiSingoloPagamentoField = value;
			}
		}
	}

	public enum ct0000000016_datiPagamentoTipoVersamento {

		/// <remarks/>
		BBT,

		/// <remarks/>
		BP,

		/// <remarks/>
		AD,

		/// <remarks/>
		CP,

		/// <remarks/>
		PO,

		/// <remarks/>
		OBEP,
	}

	public partial class ct0000000016_datiSingoloPagamento {

		public string parametriAggiuntiviSingoloVersamento { get; set; }

	}

	public enum ct0000000016_datiRestituitiCodiceEsitoPagamento {

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("0")]
		Item0,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("1")]
		Item1,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("2")]
		Item2,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("3")]
		Item3,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("4")]
		Item4,
	}

	public partial class ct0000000017_pdpRichiediStornoRT {

		public string identificativoUnivocoVersamento { get; set; }

	}

	public partial class ct0000000018_pdpRichiediStornoRTResult {

		public ct0000000018_pdpRichiediStornoRTResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000018_pdpRichiediStornoRTResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }

	}

	public enum ct0000000018_pdpRichiediStornoRTResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000018_pdpRichiediStornoRTResultCodiceErrore {

		/// <remarks/>
		PDP_IUV_NON_TROVATO,

		/// <remarks/>
		PDP_RPT_NON_TROVATA,

		/// <remarks/>
		PDP_RT_NON_DISPONIBILE,

		/// <remarks/>
		PDP_INTEGRAZIONE_NODO,
	}

	public partial class ct0000000019_pdpChiediSceltaWISP {

		public string keyPA { get; set; }

		public string keyWISP { get; set; }

	}

	public partial class ct0000000020_pdpChiediSceltaWISPResult {

		private ct0000000020_datiRestituiti datiRestituitiField;

		public ct0000000020_pdpChiediSceltaWISPResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000020_pdpChiediSceltaWISPResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000020_pdpChiediSceltaWISPResult() {
			this.datiRestituitiField = new ct0000000020_datiRestituiti();
		}

		public ct0000000020_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000020_pdpChiediSceltaWISPResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000020_pdpChiediSceltaWISPResultCodiceErrore {

		/// <remarks/>
		PDP_INTEGRAZIONE_NODO,

		/// <remarks/>
		PDP_ERRORE_NAMESPACE_NON_CORRETTO,

		/// <remarks/>
		PDP_GEN_ERRORE_SINTASSI,

		/// <remarks/>
		PDP_GEN_ACCESSO_NON_AUTORIZZATO,

		/// <remarks/>
		PDP_GEN_BU_NON_TROVATA,

		/// <remarks/>
		PDP_GEN_DECODIFICA_PARAM,

		/// <remarks/>
		PDP_GEN_RICHIESTA_NON_SUPPORTATA,

		/// <remarks/>
		PDP_ERRORE_INTERNO_XSD,

		/// <remarks/>
		PDP_LINEA_ERRORE_SINTASSI,

		/// <remarks/>
		PDP_ERRORE_RITORNO_XSD,

		/// <remarks/>
		PDP_ERRORE_INTERNO,
	}

	public partial class ct0000000020_datiRestituiti {

		public ct0000000020_datiRestituitiEffettuazioneScelta effettuazioneScelta { get; set; }

		public string identificativoPSP { get; set; }

		public string identificativoIntermediarioPSP { get; set; }

		public string identificativoCanale { get; set; }

		public ct0000000020_datiRestituitiTipoVersamento tipoVersamento { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool tipoVersamentoSpecified { get; set; }

	}

	public enum ct0000000020_datiRestituitiEffettuazioneScelta {

		/// <remarks/>
		SI,

		/// <remarks/>
		NO,
	}

	public enum ct0000000020_datiRestituitiTipoVersamento {

		/// <remarks/>
		BBT,

		/// <remarks/>
		BP,

		/// <remarks/>
		AD,

		/// <remarks/>
		CP,

		/// <remarks/>
		PO,

		/// <remarks/>
		OBEP,
	}

	public partial class ct0000000021_pdpVerificaMarcaDaBolloDigitale {

		public string documentoAbbinato { get; set; }

		public string marcaDaBolloDigitale { get; set; }

	}

	public partial class ct0000000022_pdpVerificaMarcaDaBolloDigitaleResult {

		public ct0000000022_pdpVerificaMarcaDaBolloDigitaleResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000022_pdpVerificaMarcaDaBolloDigitaleResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }

	}

	public enum ct0000000022_pdpVerificaMarcaDaBolloDigitaleResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000022_pdpVerificaMarcaDaBolloDigitaleResultCodiceErrore {

		/// <remarks/>
		PDP_FIRMA_NON_VALIDA,

		/// <remarks/>
		PDP_IMPRONTA_DOCUMENTO_ASSENTE,

		/// <remarks/>
		PDP_IMPRONTA_DOCUMENTO_ERRATA,
	}

	public partial class ct0000000023_dpVerificaPagamentoInAttesa {

		public string identificativoUnivocoVersamento { get; set; }

		public ct0000000023_dpVerificaPagamentoInAttesaContestoDiRichiesta contestoDiRichiesta { get; set; }

	}

	public enum ct0000000023_dpVerificaPagamentoInAttesaContestoDiRichiesta {

		/// <remarks/>
		VR,

		/// <remarks/>
		AR,
	}

	public partial class ct0000000024_dpVerificaPagamentoInAttesaResult {

		private ct0000000024_datiRestituiti datiRestituitiField;

		public ct0000000024_dpVerificaPagamentoInAttesaResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000024_dpVerificaPagamentoInAttesaResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000024_dpVerificaPagamentoInAttesaResult() {
			this.datiRestituitiField = new ct0000000024_datiRestituiti();
		}

		public ct0000000024_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000024_dpVerificaPagamentoInAttesaResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000024_dpVerificaPagamentoInAttesaResultCodiceErrore {

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		WS_IUV_NON_TROVATO,

		/// <remarks/>
		WS_PAGAMENTO_ANNULLATO,

		/// <remarks/>
		WS_PAGAMENTO_IN_CORSO,

		/// <remarks/>
		WS_PAGAMENTO_DUPLICATO,

		/// <remarks/>
		WS_PAGAMENTO_SCADUTO,

		/// <remarks/>
		WS_CONTESTO_RICHIESTA_SCONOSCIUTO,
	}

	public partial class ct0000000024_datiRestituiti {

		private ct0000000024_datiPagamentoInAttesa datiPagamentoInAttesaField;

		public string identificativoBU { get; set; }

		public string identificativoUnivocoVersamento { get; set; }


		public ct0000000024_datiRestituiti() {
			this.datiPagamentoInAttesaField = new ct0000000024_datiPagamentoInAttesa();
		}

		public ct0000000024_datiPagamentoInAttesa datiPagamentoInAttesa {
			get {
				return this.datiPagamentoInAttesaField;
			}
			set {
				this.datiPagamentoInAttesaField = value;
			}
		}
	}

	public partial class ct0000000024_datiPagamentoInAttesa {

		private ct0000000024_notificaCallback notificaCallbackField;

		private ct0000000024_soggettoPagatore soggettoPagatoreField;

		private List<ct0000000024_datiSingoloVersamento> datiSingoloVersamentoField;

		public System.DateTime dataScadenzaPagamento { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool dataScadenzaPagamentoSpecified { get; set; }

		public string parametriAggiuntivi { get; set; }

		public string causaleVersamentoEsplicitaPSP { get; set; }


		public ct0000000024_datiPagamentoInAttesa() {
			this.datiSingoloVersamentoField = new List<ct0000000024_datiSingoloVersamento>();
			this.soggettoPagatoreField = new ct0000000024_soggettoPagatore();
			this.notificaCallbackField = new ct0000000024_notificaCallback();
		}

		public ct0000000024_notificaCallback notificaCallback {
			get {
				return this.notificaCallbackField;
			}
			set {
				this.notificaCallbackField = value;
			}
		}

		public ct0000000024_soggettoPagatore soggettoPagatore {
			get {
				return this.soggettoPagatoreField;
			}
			set {
				this.soggettoPagatoreField = value;
			}
		}

		public List<ct0000000024_datiSingoloVersamento> datiSingoloVersamento {
			get {
				return this.datiSingoloVersamentoField;
			}
			set {
				this.datiSingoloVersamentoField = value;
			}
		}
	}

	public partial class ct0000000024_notificaCallback {

		public string callbackURL { get; set; }

		public string callbackUsername { get; set; }

		public string callbackPassword { get; set; }

	}

	public partial class ct0000000024_soggettoPagatore {

		public ct0000000024_soggettoPagatoreTipoIdentificativoUnivocoPagatore tipoIdentificativoUnivocoPagatore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool tipoIdentificativoUnivocoPagatoreSpecified { get; set; }

		public string codiceIdentificativoUnivocoPagatore { get; set; }

		public string anagraficaPagatore { get; set; }

		public string indirizzoPagatore { get; set; }

		public string civicoPagatore { get; set; }

		public string capPagatore { get; set; }

		public string localitaPagatore { get; set; }

		public string provinciaPagatore { get; set; }

		public string nazionePagatore { get; set; }

		public string emailPagatore { get; set; }

	}

	public enum ct0000000024_soggettoPagatoreTipoIdentificativoUnivocoPagatore {

		/// <remarks/>
		F,

		/// <remarks/>
		G,
	}

	public partial class ct0000000024_datiSingoloVersamento {

		public string identificativoServizio { get; set; }

		public decimal importoSingoloVersamento { get; set; }

		public decimal commissioneCaricoPA { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool commissioneCaricoPASpecified { get; set; }

		public string credenzialiPagatore { get; set; }

		public string descrizioneTestualeCausaleVersamento { get; set; }

		public string parametriAggiuntiviSingoloVersamento { get; set; }

	}

	public partial class ct0000000025_dpInviaEsitoPagamento {

		public string identificativoUnivocoVersamento { get; set; }

		public string codiceContestoPagamento { get; set; }

		public ct0000000025_dpInviaEsitoPagamentoEsitoPagamento esitoPagamento { get; set; }

	}

	public enum ct0000000025_dpInviaEsitoPagamentoEsitoPagamento {

		/// <remarks/>
		INOLTRATO,

		/// <remarks/>
		AUTORIZZATO,

		/// <remarks/>
		ESEGUITO,

		/// <remarks/>
		ESEGUITO_PARZIALMENTE,

		/// <remarks/>
		NON_ESEGUITO,

		/// <remarks/>
		NON_ESEGUITO_DECORRENZA,

		/// <remarks/>
		CANCELLATO,

		/// <remarks/>
		CANCELLATO_SCADENZA,

		/// <remarks/>
		STORNATO,

		/// <remarks/>
		REVOCATO,

		/// <remarks/>
		ACCETTATO,
	}

	public partial class ct0000000026_dpInviaEsitoPagamentoResult {

		private ct0000000026_datiRestituiti datiRestituitiField;

		public ct0000000026_dpInviaEsitoPagamentoResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000026_dpInviaEsitoPagamentoResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000026_dpInviaEsitoPagamentoResult() {
			this.datiRestituitiField = new ct0000000026_datiRestituiti();
		}

		public ct0000000026_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000026_dpInviaEsitoPagamentoResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000026_dpInviaEsitoPagamentoResultCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		WS_PAGAMENTO_SCONOSCIUTO,

		/// <remarks/>
		WS_PAGAMENTO_STATO_NON_VALIDO,

		/// <remarks/>
		WS_RT_NON_DISPONIBILE,
	}

	public partial class ct0000000026_datiRestituiti {

		public string identificativoUnivocoVersamento { get; set; }

	}

	public partial class ct0000000001_pdpChiediFlussoRendicontazioneType {

		public string identificativoFlusso { get; set; }

		public string idServizio { get; set; }

	}

	public partial class ct0000000002_pdpChiediFlussoRendicontazioneResultType {

		public ct0000000002_pdpChiediFlussoRendicontazioneResultTypeEsitoOperazione esitoOperazione { get; set; }

		public ct0000000002_pdpChiediFlussoRendicontazioneResultTypeCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }

		public string flussoXml { get; set; }

	}

	public enum ct0000000002_pdpChiediFlussoRendicontazioneResultTypeEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000002_pdpChiediFlussoRendicontazioneResultTypeCodiceErrore {

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		WS_FLUSSO_REND_NON_DISPONIBILE,

		/// <remarks/>
		WS_SERVIZIO_NON_AUTORIZZATO,

		/// <remarks/>
		PDP_ID_FLUSSO_NON_TROVATO,

		/// <remarks/>
		PDP_GEN_DECODIFICA_PARAM,

		/// <remarks/>
		PDP_ERRORE_INTERNO,
	}

	public partial class ct0000000003_pdpChiediElencoFlussiRendicontazioneType {

		public System.DateTime dataOraFlusso { get; set; }

	}

	public partial class ct0000000004_pdpChiediElencoFlussiRendicontazioneResultType {

		private List<ct0000000005_flussoType> flussoField;

		public ct0000000004_pdpChiediElencoFlussiRendicontazioneResultTypeEsitoOperazione esitoOperazione { get; set; }

		public ct0000000004_pdpChiediElencoFlussiRendicontazioneResultTypeCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }

		public string totRestituiti { get; set; }


		public ct0000000004_pdpChiediElencoFlussiRendicontazioneResultType() {
			this.flussoField = new List<ct0000000005_flussoType>();
		}

		public List<ct0000000005_flussoType> flusso {
			get {
				return this.flussoField;
			}
			set {
				this.flussoField = value;
			}
		}
	}

	public enum ct0000000004_pdpChiediElencoFlussiRendicontazioneResultTypeEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000004_pdpChiediElencoFlussiRendicontazioneResultTypeCodiceErrore {

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		WS_FLUSSO_REND_NON_DISPONIBILE,
	}

	public partial class ct0000000005_flussoType {

		public string identificativoFlusso { get; set; }

		public System.DateTime dataOraFlusso { get; set; }

	}

	public partial class ct0000000006_pdpEsitiRTType {

		public string idServizio { get; set; }

		public string idOperazione { get; set; }

		public System.DateTime dataInizio { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool dataInizioSpecified { get; set; }

		public System.DateTime dataFine { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool dataFineSpecified { get; set; }

		public string identificativoUnivocoVersamento { get; set; }

		public string codiceFiscale { get; set; }

	}

	public partial class ct0000000007_pdpEsitiRTResultType {

		private List<ct0000000008_ricevutaTelematicaType> ricevutaTelematicaField;

		public ct0000000007_pdpEsitiRTResultTypeEsitoOperazione esitoOperazione { get; set; }

		public ct0000000007_pdpEsitiRTResultTypeCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }

		public string identificativoDominio { get; set; }

		public string identificativoUB { get; set; }

		public string denominazoneUB { get; set; }


		public ct0000000007_pdpEsitiRTResultType() {
			this.ricevutaTelematicaField = new List<ct0000000008_ricevutaTelematicaType>();
		}

		public List<ct0000000008_ricevutaTelematicaType> ricevutaTelematica {
			get {
				return this.ricevutaTelematicaField;
			}
			set {
				this.ricevutaTelematicaField = value;
			}
		}
	}

	public enum ct0000000007_pdpEsitiRTResultTypeEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000007_pdpEsitiRTResultTypeCodiceErrore {

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		WS_ESITI_RT_NESSUN_RISULTATO,

		/// <remarks/>
		WS_ESITI_RT_TROPPI_RISULTAT,
	}

	public partial class ct0000000008_ricevutaTelematicaType {

		private List<ct0000000009_datiSingoloPagamentoType> datiSingoloPagamentoField;

		public string identificativoUnivocoVersamento { get; set; }

		public string idTenant { get; set; }

		public System.DateTime dataEsecuzionePagamento { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool dataEsecuzionePagamentoSpecified { get; set; }

		public System.DateTime dataInvioRt { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool dataInvioRtSpecified { get; set; }

		public string firmaRicevuta { get; set; }

		public string codiceContestoPagamento { get; set; }

		public string codiceEsitoPagamento { get; set; }

		public string tipoIdentificativoUnivocoAttestante { get; set; }

		public string codiceIdentificativoUnivocoAttestante { get; set; }

		public string denominazioneAttestante { get; set; }

		public ct0000000008_ricevutaTelematicaTypeTipoIdentificativoUnivocoPagatore tipoIdentificativoUnivocoPagatore { get; set; }

		public string codiceIdentificativoUnivocoPagatore { get; set; }

		public string anagraficaPagatore { get; set; }

		public string capPagatore { get; set; }

		public string civicoPagatore { get; set; }

		public string emailPagatore { get; set; }

		public string indirizzoPagatore { get; set; }

		public string localitaPagatore { get; set; }

		public string nazionePagatore { get; set; }

		public string provinciaPagatore { get; set; }


		public ct0000000008_ricevutaTelematicaType() {
			this.datiSingoloPagamentoField = new List<ct0000000009_datiSingoloPagamentoType>();
		}

		public List<ct0000000009_datiSingoloPagamentoType> datiSingoloPagamento {
			get {
				return this.datiSingoloPagamentoField;
			}
			set {
				this.datiSingoloPagamentoField = value;
			}
		}
	}

	public enum ct0000000008_ricevutaTelematicaTypeTipoIdentificativoUnivocoPagatore {

		/// <remarks/>
		F,

		/// <remarks/>
		G,
	}

	public partial class ct0000000009_datiSingoloPagamentoType {

		public string idServizio { get; set; }

		public decimal importoSingoloVersamento { get; set; }

		public string causaleVersamento { get; set; }

		public string tipoDatiSpecificiRiscossione { get; set; }

		public string datiSpecificiRiscossione { get; set; }

		public string identUnivocoRiscossione { get; set; }

		public string ordinePagamento { get; set; }

		public string idFlusso { get; set; }

		public string identificativoUnivocoRegolamento { get; set; }

		public string dataRegolamento { get; set; }

		public string capitoloDiBilancio { get; set; }

		public string provvisorioEntrata { get; set; }

		public string ibanAccredito { get; set; }

	}

	public partial class ct0000000027_pdpAttivaRpt {

		private ct0000000027_datiPagamentoInAttesa datiPagamentoInAttesaField;

		public string callbackURL { get; set; }


		public ct0000000027_pdpAttivaRpt() {
			this.datiPagamentoInAttesaField = new ct0000000027_datiPagamentoInAttesa();
		}

		public ct0000000027_datiPagamentoInAttesa datiPagamentoInAttesa {
			get {
				return this.datiPagamentoInAttesaField;
			}
			set {
				this.datiPagamentoInAttesaField = value;
			}
		}
	}

	public partial class ct0000000027_datiPagamentoInAttesa {

		public string identificativoUnivocoVersamento { get; set; }

	}

	public partial class ct0000000027_pdpAttivaRptResultType {

		private ct0000000027_datiRestituiti datiRestituitiField;

		public ct0000000027_pdpAttivaRptResultTypeEsitoOperazione esitoOperazione { get; set; }

		public ct0000000027_pdpAttivaRptResultTypeCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }


		public ct0000000027_pdpAttivaRptResultType() {
			this.datiRestituitiField = new ct0000000027_datiRestituiti();
		}

		public ct0000000027_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000027_pdpAttivaRptResultTypeEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000027_pdpAttivaRptResultTypeCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		WS_IUV_NON_TROVATO,

		/// <remarks/>
		WS_PAGAMENTO_IN_CORSO,
	}

	public partial class ct0000000027_datiRestituiti {

		public string identificativoUnivocoVersamento { get; set; }

		public string redirectURL { get; set; }

		public string codiceContestoPagamento { get; set; }

	}

	public partial class ct0000000028_pdpRichiediAvviso {

		public string identificativoUnivocoVersamento { get; set; }

	}

	public partial class ct0000000028_pdpRichiediAvvisoResult {

		private ct0000000028_datiRestituiti datiRestituitiField;

		public ct0000000028_pdpRichiediAvvisoResultEsitoOperazione esitoOperazione { get; set; }

		public ct0000000028_pdpRichiediAvvisoResultCodiceErrore codiceErrore { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool codiceErroreSpecified { get; set; }

		public string identificativoUnivocoVersamento { get; set; }

		public string codiceContestoPagamento { get; set; }


		public ct0000000028_pdpRichiediAvvisoResult() {
			this.datiRestituitiField = new ct0000000028_datiRestituiti();
		}

		public ct0000000028_datiRestituiti datiRestituiti {
			get {
				return this.datiRestituitiField;
			}
			set {
				this.datiRestituitiField = value;
			}
		}
	}

	public enum ct0000000028_pdpRichiediAvvisoResultEsitoOperazione {

		/// <remarks/>
		OK,

		/// <remarks/>
		KO,
	}

	public enum ct0000000028_pdpRichiediAvvisoResultCodiceErrore {

		/// <remarks/>
		WS_DOMINIO_UB_MANCANTE,

		/// <remarks/>
		WS_PARAMETRI_MANCANTI,

		/// <remarks/>
		WS_ERRORE_INTERNO,

		/// <remarks/>
		WS_IUV_NON_TROVATO,
	}

	public partial class ct0000000028_datiRestituiti {

		public string pdfFile { get; set; }

	}

	public partial class ct0000000012_tipoStoricoRPT {

		private List<ct0000000012_tipoElementoListaStorico> elementoListaStoricoField;

		public ct0000000012_tipoStoricoRPT() {
			this.elementoListaStoricoField = new List<ct0000000012_tipoElementoListaStorico>();
		}

		public List<ct0000000012_tipoElementoListaStorico> elementoListaStorico {
			get {
				return this.elementoListaStoricoField;
			}
			set {
				this.elementoListaStoricoField = value;
			}
		}
	}

	public partial class ct0000000016_allegatoRicevuta {

		public ct0000000016_allegatoRicevutaTipoAllegatoRicevuta tipoAllegatoRicevuta { get; set; }

		public string testoAllegato { get; set; }

	}

	public enum ct0000000016_allegatoRicevutaTipoAllegatoRicevuta {

		/// <remarks/>
		ES,

		/// <remarks/>
		BD,
	}

	public partial class ct0000000016_istitutoAttestante {

		public ct0000000016_istitutoAttestanteTipoIdentificativoUnivocoAttestante tipoIdentificativoUnivocoAttestante { get; set; }

		public string codiceIdentificativoUnivocoAttestante { get; set; }

		public string denominazioneAttestante { get; set; }

		public string codiceUnitOperAttestante { get; set; }

		public string denomUnitOperAttestante { get; set; }

		public string indirizzoAttestante { get; set; }

		public string civicoAttestante { get; set; }

		public string capAttestante { get; set; }

		public string localitaAttestante { get; set; }

		public string provinciaAttestante { get; set; }

		public string nazioneAttestante { get; set; }

	}

	public enum ct0000000016_istitutoAttestanteTipoIdentificativoUnivocoAttestante {

		/// <remarks/>
		G,

		/// <remarks/>
		A,

		/// <remarks/>
		B,
	}

	public partial class ct0000000016_enteBeneficiario {

		public ct0000000016_enteBeneficiarioTipoIdentificativoUnivocoBeneficiario tipoIdentificativoUnivocoBeneficiario { get; set; }

		public string codiceIdentificativoUnivocoBeneficiario { get; set; }

		public string denominazioneBeneficiario { get; set; }

		public string codiceUnitOperBeneficiario { get; set; }

		public string denomUnitOperBeneficiario { get; set; }

		public string indirizzoBeneficiario { get; set; }

		public string civicoBeneficiario { get; set; }

		public string capBeneficiario { get; set; }

		public string localitaBeneficiario { get; set; }

		public string provinciaBeneficiario { get; set; }

		public string nazioneBeneficiario { get; set; }

	}

	public enum ct0000000016_enteBeneficiarioTipoIdentificativoUnivocoBeneficiario {

		/// <remarks/>
		G,
	}

	public partial class ct0000000016_soggettoVersante {

		public ct0000000016_soggettoVersanteTipoIdentificativoUnivocoVersante tipoIdentificativoUnivocoVersante { get; set; }

		public string codiceIdentificativoUnivocoVersante { get; set; }

		public string anagraficaVersante { get; set; }

		public string indirizzoVersante { get; set; }

		public string civicoVersante { get; set; }

		public string capVersante { get; set; }

		public string localitaVersante { get; set; }

		public string provinciaVersante { get; set; }

		public string nazioneVersante { get; set; }

		public string emailVersante { get; set; }

	}

	public enum ct0000000016_soggettoVersanteTipoIdentificativoUnivocoVersante {

		/// <remarks/>
		F,

		/// <remarks/>
		G,
	}

	public partial class ct0000000016_soggettoPagatore {

		public ct0000000016_soggettoPagatoreTipoIdentificativoUnivocoPagatore tipoIdentificativoUnivocoPagatore { get; set; }

		public string codiceIdentificativoUnivocoPagatore { get; set; }

		public string anagraficaPagatore { get; set; }

		public string indirizzoPagatore { get; set; }

		public string civicoPagatore { get; set; }

		public string capPagatore { get; set; }

		public string localitaPagatore { get; set; }

		public string provinciaPagatore { get; set; }

		public string nazionePagatore { get; set; }

		public string emailPagatore { get; set; }

	}

	public enum ct0000000016_soggettoPagatoreTipoIdentificativoUnivocoPagatore {

		/// <remarks/>
		F,

		/// <remarks/>
		G,
	}
}
