
/*
Easy
Copyright (C) 2021 Università degli Studi di Catania (www.unict.it)
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml;
using System.ServiceModel;
using System.Runtime.Serialization;

namespace pagoPaService.PayPA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pmpay.it/ws/payPA/", ConfigurationName="PayPA.PayPA")]
    public interface PayPA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/Pagamento", ReplyAction="*")]
        pagoPaService.PayPA.PagamentoResponse Pagamento(pagoPaService.PayPA.PagamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/Pagamento", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<pagoPaService.PayPA.PagamentoResponse> PagamentoAsync( pagoPaService.PayPA.PagamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/GetRT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRT(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/GetRT", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetRTAsync(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/GetBOLLO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetBOLLOResponse")]
        string GetBOLLO(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/GetBOLLO", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetBOLLOResponse")]
        System.Threading.Tasks.Task<string> GetBOLLOAsync(string content);

        [System.ServiceModel.OperationContractAttribute(Action = "http://pmpay.it/ws/payPA/PagamentoEsistente", ReplyAction = "*")]
        pagoPaService.PayPA.PagamentoResponse PagamentoEsistente(pagoPaService.PayPA.PagamentoEsistenteRequest request);


        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/PagamentoEsistente", ReplyAction="*")]
        System.Threading.Tasks.Task<pagoPaService.PayPA.PagamentoResponse> PagamentoEsistenteAsync(pagoPaService.PayPA.PagamentoEsistenteRequest reques);
        
        // CODEGEN: Generating message contract since the operation RegistraPagamento is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/RegistraPagamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        pagoPaService.PayPA.RegistraPagamentoResponse1 RegistraPagamento(pagoPaService.PayPA.RegistraPagamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/RegistraPagamento", ReplyAction="*")]
        System.Threading.Tasks.Task<pagoPaService.PayPA.RegistraPagamentoResponse1> RegistraPagamentoAsync(pagoPaService.PayPA.RegistraPagamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/PagamentoEsistenteBollettino", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        pagoPaService.PayPA.PagamentoEsistenteBollettinoResponse1 PagamentoEsistenteBollettino(pagoPaService.PayPA.PagamentoEsistenteBollettinoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://pmpay.it/ws/payPA/PagamentoEsistenteBollettino", ReplyAction="*")]
        System.Threading.Tasks.Task<pagoPaService.PayPA.PagamentoEsistenteBollettinoResponse1> PagamentoEsistenteBollettinoAsync(pagoPaService.PayPA.PagamentoEsistenteBollettinoRequest request);
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PagamentoRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Pagamento", Namespace = "http://pmpay.it/ws/PayPA/", Order = 0)]
        public pagoPaService.PayPA.PagamentoRequestBody Body;

        public PagamentoRequest() {
        }

        public PagamentoRequest(pagoPaService.PayPA.PagamentoRequestBody Body) {
            this.Body = Body;
        }
    }


    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PagamentoEsistenteRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PagamentoEsistente", Namespace = "http://pmpay.it/ws/PayPA/", Order = 0)]
        public pagoPaService.PayPA.PagamentoEsistenteRequestBody Body;

        public PagamentoEsistenteRequest() {
        }

        public PagamentoEsistenteRequest(pagoPaService.PayPA.PagamentoEsistenteRequestBody Body) {
            this.Body = Body;
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://pmpay.it/ws/PayPA/")]
    public partial class PagamentoRequestBody {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string content;

        public PagamentoRequestBody() {
        }

        public PagamentoRequestBody(string content) {
            this.content = content;
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://pmpay.it/ws/PayPA/")]
    public partial class PagamentoEsistenteRequestBody {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string content;

        public PagamentoEsistenteRequestBody() {
        }

        public PagamentoEsistenteRequestBody(string content) {
            this.content = content;
        }
    }


    //response
    //    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://pmpay.it/ws/payPA/")]
    //[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagamentoResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagamentoResponse", Namespace="http://pmpay.it/ws/PayPA/", Order=0)]
        public PagamentoResponseBody response;

        
        public PagamentoResponse() {
        }

        public PagamentoResponse(string Body) {
            this.response = new PagamentoResponseBody(Body);
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://pmpay.it/ws/PayPA/")]
    public partial class PagamentoResponseBody {

        [System.Runtime.Serialization.DataMemberAttribute(Name="response",EmitDefaultValue = false, Order = 0)]
        public string PagamentoResult;

        public PagamentoResponseBody() {
        }

        public PagamentoResponseBody(string PagamentoResult) {
            this.PagamentoResult = PagamentoResult;
        }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pmpay.it/ws/PayPA/")]
    public partial class RegistraPagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("request");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pmpay.it/ws/PayPA/")]
    public partial class Pagamento :object, System.ComponentModel.INotifyPropertyChanged {

        private string requestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("request");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pmpay.it/ws/payPA/")]
    public partial class RegistraPagamentoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

 
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraPagamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmpay.it/ws/payPA/", Order=0)]
        public pagoPaService.PayPA.RegistraPagamento RegistraPagamento;
        
        public RegistraPagamentoRequest() {
        }
        
        public RegistraPagamentoRequest(pagoPaService.PayPA.RegistraPagamento RegistraPagamento) {
            this.RegistraPagamento = RegistraPagamento;
        }
    }


 

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraPagamentoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmpay.it/ws/payPA/", Order=0)]
        public pagoPaService.PayPA.RegistraPagamentoResponse RegistraPagamentoResponse;
        
        public RegistraPagamentoResponse1() {
        }
        
        public RegistraPagamentoResponse1(pagoPaService.PayPA.RegistraPagamentoResponse RegistraPagamentoResponse) {
            this.RegistraPagamentoResponse = RegistraPagamentoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pmpay.it/ws/payPA/")]
    public partial class PagamentoEsistenteBollettinoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string esitoField;
        
        private string erroreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
                this.RaisePropertyChanged("esito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errore {
            get {
                return this.erroreField;
            }
            set {
                this.erroreField = value;
                this.RaisePropertyChanged("errore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PagamentoEsistenteBollettino", WrapperNamespace="http://pmpay.it/ws/payPA/", IsWrapped=true)]
    public partial class PagamentoEsistenteBollettinoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmpay.it/ws/payPA/", Order=0)]
        public string request;
        
        public PagamentoEsistenteBollettinoRequest() {
        }
        
        public PagamentoEsistenteBollettinoRequest(string request) {
            this.request = request;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagamentoEsistenteBollettinoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmpay.it/ws/payPA/", Order=0)]
        public pagoPaService.PayPA.PagamentoEsistenteBollettinoResponse PagamentoEsistenteBollettinoResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bollettino;
        
        public PagamentoEsistenteBollettinoResponse1() {
        }
        
        public PagamentoEsistenteBollettinoResponse1(pagoPaService.PayPA.PagamentoEsistenteBollettinoResponse PagamentoEsistenteBollettinoResponse, byte[] bollettino) {
            this.PagamentoEsistenteBollettinoResponse = PagamentoEsistenteBollettinoResponse;
            this.bollettino = bollettino;
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PayPAChannel : pagoPaService.PayPA.PayPA, System.ServiceModel.IClientChannel {
    }
  
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PayPAClient : System.ServiceModel.ClientBase<pagoPaService.PayPA.PayPA>, pagoPaService.PayPA.PayPA {

    public PayPAClient() {
    }

    public PayPAClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }

    public PayPAClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }

    public PayPAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }

    public PayPAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }

     [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pagoPaService.PayPA.PagamentoResponse pagoPaService.PayPA.PayPA.Pagamento(pagoPaService.PayPA.PagamentoRequest request) {
            return base.Channel.Pagamento(request);
        }

        public string Pagamento(string content) {
            pagoPaService.PayPA.PagamentoRequest inValue = new pagoPaService.PayPA.PagamentoRequest();
            inValue.Body = new pagoPaService.PayPA.PagamentoRequestBody();
            inValue.Body.content = content;
            pagoPaService.PayPA.PagamentoResponse retVal = ((pagoPaService.PayPA.PayPA)(this)).Pagamento(inValue);
            return retVal.response.PagamentoResult;
        }

    public System.Threading.Tasks.Task<pagoPaService.PayPA.PagamentoResponse> PagamentoAsync(pagoPaService.PayPA.PagamentoRequest request) {
        return base.Channel.PagamentoAsync(request);
    }

    public string GetRT(string content) {
        return base.Channel.GetRT(content);
    }

    public System.Threading.Tasks.Task<string> GetRTAsync(string content) {
        return base.Channel.GetRTAsync(content);
    }

    public string GetBOLLO(string content) {
        return base.Channel.GetBOLLO(content);
    }

    public System.Threading.Tasks.Task<string> GetBOLLOAsync(string content) {
        return base.Channel.GetBOLLOAsync(content);
    }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pagoPaService.PayPA.PagamentoResponse pagoPaService.PayPA.PayPA.PagamentoEsistente(pagoPaService.PayPA.PagamentoEsistenteRequest request) {
            return base.Channel.PagamentoEsistente(request);
        }

        public string PagamentoEsistente(string content) {
            pagoPaService.PayPA.PagamentoRequest inValue = new pagoPaService.PayPA.PagamentoRequest();
            inValue.Body = new pagoPaService.PayPA.PagamentoRequestBody();
            inValue.Body.content = content;
            pagoPaService.PayPA.PagamentoResponse retVal = ((pagoPaService.PayPA.PayPA)(this)).Pagamento(inValue);
            return retVal.response.PagamentoResult;
        }

        public System.Threading.Tasks.Task<pagoPaService.PayPA.PagamentoResponse> PagamentoEsistenteAsync(pagoPaService.PayPA.PagamentoEsistenteRequest request) {
        return base.Channel.PagamentoEsistenteAsync(request);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    pagoPaService.PayPA.RegistraPagamentoResponse1 pagoPaService.PayPA.PayPA.RegistraPagamento(pagoPaService.PayPA.RegistraPagamentoRequest request) {
        return base.Channel.RegistraPagamento(request);
    }

    public pagoPaService.PayPA.RegistraPagamentoResponse RegistraPagamento(pagoPaService.PayPA.RegistraPagamento RegistraPagamento1) {
        pagoPaService.PayPA.RegistraPagamentoRequest inValue = new pagoPaService.PayPA.RegistraPagamentoRequest();
        inValue.RegistraPagamento = RegistraPagamento1;
        pagoPaService.PayPA.RegistraPagamentoResponse1 retVal = ((pagoPaService.PayPA.PayPA)(this)).RegistraPagamento(inValue);
        return retVal.RegistraPagamentoResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<pagoPaService.PayPA.RegistraPagamentoResponse1> pagoPaService.PayPA.PayPA.RegistraPagamentoAsync(pagoPaService.PayPA.RegistraPagamentoRequest request) {
        return base.Channel.RegistraPagamentoAsync(request);
    }

    public System.Threading.Tasks.Task<pagoPaService.PayPA.RegistraPagamentoResponse1> RegistraPagamentoAsync(pagoPaService.PayPA.RegistraPagamento RegistraPagamento) {
        pagoPaService.PayPA.RegistraPagamentoRequest inValue = new pagoPaService.PayPA.RegistraPagamentoRequest();
        inValue.RegistraPagamento = RegistraPagamento;
        return ((pagoPaService.PayPA.PayPA)(this)).RegistraPagamentoAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    pagoPaService.PayPA.PagamentoEsistenteBollettinoResponse1 pagoPaService.PayPA.PayPA.PagamentoEsistenteBollettino(pagoPaService.PayPA.PagamentoEsistenteBollettinoRequest request) {
        return base.Channel.PagamentoEsistenteBollettino(request);
    }

    public pagoPaService.PayPA.PagamentoEsistenteBollettinoResponse PagamentoEsistenteBollettino(string request, out byte[] bollettino) {
        pagoPaService.PayPA.PagamentoEsistenteBollettinoRequest inValue = new pagoPaService.PayPA.PagamentoEsistenteBollettinoRequest();
        inValue.request = request;
        pagoPaService.PayPA.PagamentoEsistenteBollettinoResponse1 retVal = ((pagoPaService.PayPA.PayPA)(this)).PagamentoEsistenteBollettino(inValue);
        bollettino = retVal.bollettino;
        return retVal.PagamentoEsistenteBollettinoResponse;
    }

    public System.Threading.Tasks.Task<pagoPaService.PayPA.PagamentoEsistenteBollettinoResponse1> PagamentoEsistenteBollettinoAsync(pagoPaService.PayPA.PagamentoEsistenteBollettinoRequest request) {
        return base.Channel.PagamentoEsistenteBollettinoAsync(request);
    }
}
}
