
/*
Easy
Copyright (C) 2022 Università degli Studi di Catania (www.unict.it)
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace ritenuta770{//ritenuta770//
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class vistaForm : DataSet {
        
        private ritenuta770DataTable tableritenuta770;
        
        public vistaForm() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected vistaForm(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["ritenuta770"] != null)) {
                    this.Tables.Add(new ritenuta770DataTable(ds.Tables["ritenuta770"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ritenuta770DataTable ritenuta770 {
            get {
                return this.tableritenuta770;
            }
        }
        
        public override DataSet Clone() {
            vistaForm cln = ((vistaForm)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["ritenuta770"] != null)) {
                this.Tables.Add(new ritenuta770DataTable(ds.Tables["ritenuta770"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableritenuta770 = ((ritenuta770DataTable)(this.Tables["ritenuta770"]));
            if ((this.tableritenuta770 != null)) {
                this.tableritenuta770.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "vistaForm";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/vistaForm.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableritenuta770 = new ritenuta770DataTable();
            this.Tables.Add(this.tableritenuta770);
        }
        
        private bool ShouldSerializeritenuta770() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void ritenuta770RowChangeEventHandler(object sender, ritenuta770RowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ritenuta770DataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnesercizio;
            
            private DataColumn columncodiceritenuta770;
            
            private DataColumn columndescrizione;
            
            private DataColumn columncreatetimestamp;
            
            private DataColumn columncreateuser;
            
            private DataColumn columnlastmodtimestamp;
            
            private DataColumn columnlastmoduser;
            
            internal ritenuta770DataTable() : 
                    base("ritenuta770") {
                this.InitClass();
            }
            
            internal ritenuta770DataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn esercizioColumn {
                get {
                    return this.columnesercizio;
                }
            }
            
            internal DataColumn codiceritenuta770Column {
                get {
                    return this.columncodiceritenuta770;
                }
            }
            
            internal DataColumn descrizioneColumn {
                get {
                    return this.columndescrizione;
                }
            }
            
            internal DataColumn createtimestampColumn {
                get {
                    return this.columncreatetimestamp;
                }
            }
            
            internal DataColumn createuserColumn {
                get {
                    return this.columncreateuser;
                }
            }
            
            internal DataColumn lastmodtimestampColumn {
                get {
                    return this.columnlastmodtimestamp;
                }
            }
            
            internal DataColumn lastmoduserColumn {
                get {
                    return this.columnlastmoduser;
                }
            }
            
            public ritenuta770Row this[int index] {
                get {
                    return ((ritenuta770Row)(this.Rows[index]));
                }
            }
            
            public event ritenuta770RowChangeEventHandler ritenuta770RowChanged;
            
            public event ritenuta770RowChangeEventHandler ritenuta770RowChanging;
            
            public event ritenuta770RowChangeEventHandler ritenuta770RowDeleted;
            
            public event ritenuta770RowChangeEventHandler ritenuta770RowDeleting;
            
            public void Addritenuta770Row(ritenuta770Row row) {
                this.Rows.Add(row);
            }
            
            public ritenuta770Row Addritenuta770Row(short esercizio, string codiceritenuta770, string descrizione, System.DateTime createtimestamp, string createuser, System.DateTime lastmodtimestamp, string lastmoduser) {
                ritenuta770Row rowritenuta770Row = ((ritenuta770Row)(this.NewRow()));
                rowritenuta770Row.ItemArray = new object[] {
                        esercizio,
                        codiceritenuta770,
                        descrizione,
                        createtimestamp,
                        createuser,
                        lastmodtimestamp,
                        lastmoduser};
                this.Rows.Add(rowritenuta770Row);
                return rowritenuta770Row;
            }
            
            public ritenuta770Row FindByeserciziocodiceritenuta770(short esercizio, string codiceritenuta770) {
                return ((ritenuta770Row)(this.Rows.Find(new object[] {
                            esercizio,
                            codiceritenuta770})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                ritenuta770DataTable cln = ((ritenuta770DataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new ritenuta770DataTable();
            }
            
            internal void InitVars() {
                this.columnesercizio = this.Columns["esercizio"];
                this.columncodiceritenuta770 = this.Columns["codiceritenuta770"];
                this.columndescrizione = this.Columns["descrizione"];
                this.columncreatetimestamp = this.Columns["createtimestamp"];
                this.columncreateuser = this.Columns["createuser"];
                this.columnlastmodtimestamp = this.Columns["lastmodtimestamp"];
                this.columnlastmoduser = this.Columns["lastmoduser"];
            }
            
            private void InitClass() {
                this.columnesercizio = new DataColumn("esercizio", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnesercizio);
                this.columncodiceritenuta770 = new DataColumn("codiceritenuta770", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncodiceritenuta770);
                this.columndescrizione = new DataColumn("descrizione", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescrizione);
                this.columncreatetimestamp = new DataColumn("createtimestamp", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncreatetimestamp);
                this.columncreateuser = new DataColumn("createuser", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncreateuser);
                this.columnlastmodtimestamp = new DataColumn("lastmodtimestamp", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnlastmodtimestamp);
                this.columnlastmoduser = new DataColumn("lastmoduser", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnlastmoduser);
                this.Constraints.Add(new UniqueConstraint("vistaFormKey1", new DataColumn[] {
                                this.columnesercizio,
                                this.columncodiceritenuta770}, true));
                this.columnesercizio.AllowDBNull = false;
                this.columncodiceritenuta770.AllowDBNull = false;
                this.columndescrizione.AllowDBNull = false;
            }
            
            public ritenuta770Row Newritenuta770Row() {
                return ((ritenuta770Row)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new ritenuta770Row(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(ritenuta770Row);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ritenuta770RowChanged != null)) {
                    this.ritenuta770RowChanged(this, new ritenuta770RowChangeEvent(((ritenuta770Row)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ritenuta770RowChanging != null)) {
                    this.ritenuta770RowChanging(this, new ritenuta770RowChangeEvent(((ritenuta770Row)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ritenuta770RowDeleted != null)) {
                    this.ritenuta770RowDeleted(this, new ritenuta770RowChangeEvent(((ritenuta770Row)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ritenuta770RowDeleting != null)) {
                    this.ritenuta770RowDeleting(this, new ritenuta770RowChangeEvent(((ritenuta770Row)(e.Row)), e.Action));
                }
            }
            
            public void Removeritenuta770Row(ritenuta770Row row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ritenuta770Row : DataRow {
            
            private ritenuta770DataTable tableritenuta770;
            
            internal ritenuta770Row(DataRowBuilder rb) : 
                    base(rb) {
                this.tableritenuta770 = ((ritenuta770DataTable)(this.Table));
            }
            
            public short esercizio {
                get {
                    return ((short)(this[this.tableritenuta770.esercizioColumn]));
                }
                set {
                    this[this.tableritenuta770.esercizioColumn] = value;
                }
            }
            
            public string codiceritenuta770 {
                get {
                    return ((string)(this[this.tableritenuta770.codiceritenuta770Column]));
                }
                set {
                    this[this.tableritenuta770.codiceritenuta770Column] = value;
                }
            }
            
            public string descrizione {
                get {
                    return ((string)(this[this.tableritenuta770.descrizioneColumn]));
                }
                set {
                    this[this.tableritenuta770.descrizioneColumn] = value;
                }
            }
            
            public System.DateTime createtimestamp {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableritenuta770.createtimestampColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e);
                    }
                }
                set {
                    this[this.tableritenuta770.createtimestampColumn] = value;
                }
            }
            
            public string createuser {
                get {
                    try {
                        return ((string)(this[this.tableritenuta770.createuserColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e);
                    }
                }
                set {
                    this[this.tableritenuta770.createuserColumn] = value;
                }
            }
            
            public System.DateTime lastmodtimestamp {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableritenuta770.lastmodtimestampColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e);
                    }
                }
                set {
                    this[this.tableritenuta770.lastmodtimestampColumn] = value;
                }
            }
            
            public string lastmoduser {
                get {
                    try {
                        return ((string)(this[this.tableritenuta770.lastmoduserColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e);
                    }
                }
                set {
                    this[this.tableritenuta770.lastmoduserColumn] = value;
                }
            }
            
            public bool IscreatetimestampNull() {
                return this.IsNull(this.tableritenuta770.createtimestampColumn);
            }
            
            public void SetcreatetimestampNull() {
                this[this.tableritenuta770.createtimestampColumn] = System.Convert.DBNull;
            }
            
            public bool IscreateuserNull() {
                return this.IsNull(this.tableritenuta770.createuserColumn);
            }
            
            public void SetcreateuserNull() {
                this[this.tableritenuta770.createuserColumn] = System.Convert.DBNull;
            }
            
            public bool IslastmodtimestampNull() {
                return this.IsNull(this.tableritenuta770.lastmodtimestampColumn);
            }
            
            public void SetlastmodtimestampNull() {
                this[this.tableritenuta770.lastmodtimestampColumn] = System.Convert.DBNull;
            }
            
            public bool IslastmoduserNull() {
                return this.IsNull(this.tableritenuta770.lastmoduserColumn);
            }
            
            public void SetlastmoduserNull() {
                this[this.tableritenuta770.lastmoduserColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ritenuta770RowChangeEvent : EventArgs {
            
            private ritenuta770Row eventRow;
            
            private DataRowAction eventAction;
            
            public ritenuta770RowChangeEvent(ritenuta770Row row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public ritenuta770Row Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
