
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudio.dbo.sql   >> dbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudio.vocdbo.sql   >> vocdbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudio.vocndbo.sql   >> vocndbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudiokind.dbo.sql   >> dbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudiokind.vocdbo.sql   >> vocdbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudiokind.vocndbo.sql   >> vocndbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudiolivello.dbo.sql   >> dbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudiolivello.vocdbo.sql   >> vocdbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudiolivello.vocndbo.sql   >> vocndbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudionorma.dbo.sql   >> dbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudionorma.vocdbo.sql   >> vocdbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\corsostudionorma.vocndbo.sql   >> vocndbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_corsostudiodefaultview.dbo.sql   >> dbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_corsostudiodefaultview.vocndbo.sql   >> vocndbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_corsostudiokinddefaultview.dbo.sql   >> dbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_corsostudiokinddefaultview.vocndbo.sql   >> vocndbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_corsostudiolivellodefaultview.dbo.sql   >> dbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_corsostudiolivellodefaultview.vocndbo.sql   >> vocndbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_corsostudionormadefaultview.dbo.sql   >> dbo20210511.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_corsostudionormadefaultview.vocndbo.sql   >> vocndbo20210511.sql
