
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\accmotive.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamento.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentoattach.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentocaratteristica.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentocaratteristicaora.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\asset.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiary.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiaryora.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attivform.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\canale.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ccnlregistry_aziende.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\contratto.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\contrattokind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudio.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\costoscontodef.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\costoscontodefdettaglio.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\currency.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\diderog.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprog.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogaccesso.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didproggrupp.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\edificio.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\fasciaiseedef.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\fonteindicebibliometrico.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\geo_city.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\geo_nation.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getprogettocostoview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\inventorytree.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizione.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizioneanno.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istitutoprinc.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\lezione.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoactivitykind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoasset.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattach.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkindprogettostatuskind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettobudget.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettobudgetvariazione.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettocosto.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettokind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoproroga.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoregistry_aziende.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettorp.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettosettoreerc.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettostatuskind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotesto.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokindprogettostatuskind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocosto.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostoaccmotive.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostocontrattokind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostoinventorytree.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindaccmotive.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindcontrattokind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindinventorytree.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindtax.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostotax.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudr.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembro.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembrokind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicaz.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazkind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazregistry_aziende.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazregistry_docenti.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ratadef.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryaddress.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryclass.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfin.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfinbando.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfinbandoattach.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryreference.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_amministrativi.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_aziende.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_docenti.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_istituti.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_istitutiesteri.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_studenti.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicont.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontaltro.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogetto.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogettoora.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontlezionestud.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sede.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\settoreerc.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sospensione.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\stipendiokind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\struttura.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tax.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\titolostudio.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\upb.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackage.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackagekind.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackageupb.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accmotivesegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentodefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentodocview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentosegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetdiarydocview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetdiaryoraview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetsegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformappelloview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformdefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformerogataview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformgruppoview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformpropedview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_canaleerogataview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_contrattokinddefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiodotmasview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudioingressoview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiostatoview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_diderogdefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogdefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogdotmasview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogingressoview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogstatoview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_edificioseg_childview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_fasciaiseedefdefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_fonteindicebibliometricosegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_cityseg5view.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getprogettocostoview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getregistrydocentiamministrativi.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_inventorytreesegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneseganagstuaccview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneseganagstumastview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneseganagstusingview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneseganagstustatoview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneseganagstuview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettoactivitykinddefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettokindsegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettoudrmembrokinddefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazdefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazdocentiview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazkinddefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ratadefdefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryaddresssegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativiview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativi_personaleview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryaziendeview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryclassdefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocentiview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocenti_docview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistitutiesteriview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistitutiview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistituti_princview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryprogfinbandosegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryprogfinsegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrystudentiview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagammview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettodocview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettooraview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettosegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sededefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sedeseg_childview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sedeseg_child_aziendaview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_settoreercsegprogview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_settoreercsegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_stipendiokinddefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturadefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturaprincview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_taxsegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_titolostudiodocentiview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_upbdefaultview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_workpackagesegview.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_compute_assetdiaryora.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_GenerateDidProgCurricula.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_GenerateProgettoDetail.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateMenu.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateRules.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateSecurity.sql >> tabelle20210113.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateWebList_Redir.sql >> tabelle20210113.sql
