type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateWebList_Redir.sql 								>> tabelle.sql>> tabelle.sql

REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\accmotive.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\accordoscambiomi.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\accordoscambiomidett.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\accordoscambiomidettaz.sql                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\accordoscambiomidettlangkind.sql                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\accordoscambiomiporzanno.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\accreditokind.sql                                      >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\address.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamento.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentoattach.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentocaratteristica.sql                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentocaratteristicaora.sql                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentokind.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentokindcostoora.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ambitoareadisc.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\annoaccademico.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\aoo.sql                                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\appello.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\appelloattivform.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\appelloazionekind.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\appellokind.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\appelloprova.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\areadidattica.sql                                      >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\asset.sql                                              >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetacquire.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiary.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiaryora.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assicurazione.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ateco.sql                                              >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attach.sql                                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attivform.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attivformcaratteristica.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attivformcaratteristicaora.sql                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attivformproped.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attivformvalutazionekind.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\aula.sql                                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\aulakind.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandods.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandodsiscr.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandodsiscresito.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandodsservizio.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandodsservizioattach.sql                              >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandodsserviziodatepres.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandodsserviziorequisito.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomi.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomiallegati.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomididprogfrom.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomididprogto.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomiinsegn.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomiistitutiesteri.sql                              >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomipropedeut.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomirequisito.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomistrutturefrom.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomistruttureto.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomobilitaintkind.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\canale.sql                                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ccnl.sql                                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ccnlregistry_aziende.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\cefr.sql                                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\cefrlanglevel.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\changes.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\changeskind.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\classconsorsuale.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\classescuola.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\classescuolaarea.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\classescuolacaratteristica.sql                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\classescuolakind.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\commiss.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\commissregistry_docenti.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\compute_assetdiaryora.sql                              >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\contratto.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\contrattokind.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\contrattokindperiodo.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\convalida.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\convalidakind.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\convalidante.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\convalidato.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\convenzione.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\convenzioneattach.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudio.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudiocaratteristica.sql                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudioclassescuola.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudiokind.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudiolivello.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudionorma.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudiostruttura.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\costoscontodef.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\costoscontodefdettaglio.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\costoscontodefdettagliokind.sql                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\costoscontodefkind.sql                                 >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\currency.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\decadenza.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\delibera.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\deliberaistanza.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiar.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiaraltrekind.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiardisabilkind.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiardisabilsuppkind.sql                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiarkind.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiar_altre.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiar_altrititoli.sql                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiar_disabil.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiar_isee.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiar_titolo.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\diderog.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprog.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogaccesso.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didproganno.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogclassconsorsuale.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogcurr.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogcurrcaratteristica.sql                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogdatepiano.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didproggrupp.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didproggruppcaratteristica.sql                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogori.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogporzanno.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprograppstud.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\diniego.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\duratakind.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\edificio.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\erogazkind.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\esonero.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\esonero_carriera.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\esonero_disabil.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\esonero_titolostudio.sql                               >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\expense.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\fasciaisee.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\fasciaiseedef.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\fonteindicebibliometrico.sql                           >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\geo_city.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\geo_continent.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\geo_country.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\geo_nation.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\geo_region.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\graduatoria.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\graduatoriadesc.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\graduatoriaesiti.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\graduatoriaesitipos.sql                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\graduatoriavar.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\inquadramento.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\insegn.sql                                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\insegncaratteristica.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\insegninteg.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\insegnintegcaratteristica.sql                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\inventorytree.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\isced2013.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizione.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizioneanno.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizionebmi.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizionebmiattach.sql                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizionebmirequisito.sql                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanza.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanzaattach.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanzadichiar.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanzakind.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanza_cert.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanza_eq.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanza_imm.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanza_pas.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanza_rin.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanza_sosp.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanza_tru.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istattitolistudio.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istitutokind.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istitutoprinc.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\itineration.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\learningagrkind.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\learningagrstud.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\learningagrtrainer.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\learningagrtrainerkind.sql                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\learningagrtrainervalut.sql                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\lezione.sql                                            >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\location.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\mutuazione.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\mutuazionecaratteristica.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\mutuazionecaratteristicaora.sql                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\nace.sql                                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\naturagiur.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\nullaosta.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\nullaosta_imm.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\numerodip.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ofakind.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\orakind.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\pagamentokind.sql                                      >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\pettycash.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\pianostudio.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\pianostudioattivform.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\pianostudiostatus.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\pratica.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\prenotappello.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoactivitykind.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoasset.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattach.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkind.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettobudget.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettocosto.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettokind.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoproroga.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoregistry_aziende.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettosettoreerc.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettostatuskind.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotesto.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokind.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocosto.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostoaccmotive.sql                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostocontrattokind.sql                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostoinventorytree.sql                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokind.sql                              >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindaccmotive.sql                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindcontrattokind.sql                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindinventorytree.sql                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindtax.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostotax.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudr.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembro.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\programmami.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollo.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodestinatario.sql                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodoc.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodocelement.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodockind.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollorifkind.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\prova.sql                                              >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\provaaula.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicaz.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazkeyword.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazkind.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazkindpublicaz.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazregistry_aziende.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazregistry_docenti.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\questionario.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\questionariodom.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\questionariodomkind.sql                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\questionariodomrisp.sql                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\questionariokind.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ratadef.sql                                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ratakind.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry.sql                                           >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryaddress.sql                                    >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryclass.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfin.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfinbando.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfinbandoattach.sql                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryreference.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_amministrativi.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_aziende.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_docenti.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_istituti.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_istitutiesteri.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_studenti.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_user.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicont.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontaltro.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontaltrokind.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogetto.sql                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogettoora.sql                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontlezionestud.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sasd.sql                                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sasdgruppo.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sasdistitutokind.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sede.sql                                               >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\segst001.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sessione.sql                                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sessionekind.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\settoreerc.sql                                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sospensione.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sostenimento.sql                                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sostenimentoesito.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\staffagrteaching.sql                                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\stipendiokind.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\struttura.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\strutturakind.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\studdirittokind.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\studprenotkind.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tassaconf.sql                                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tassaconfkind.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tassacsingconf.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tassaiscrizioneconf.sql                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tassaistanzaconf.sql                                   >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tax.sql                                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tipoattform.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tipologiastudente.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tipologiastudentestruttura.sql                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirocinioappr.sql                                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirociniocandidatura.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirociniocandidaturakind.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirociniodiario.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirocinioinvioazienda.sql                              >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirocinioprogetto.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirocinioproposto.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirociniorelazione.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirociniostato.sql                                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\titolostudio.sql                                       >> tabelle.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\upb.sql                                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\valutazionekind.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\virtualuser.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackage.sql                                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackagekind.sql                                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackageupb.sql                                     >> tabelle.sql

type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateCompute_assetdiaryora.sql                      >> tabelle2.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateDidProgCurricula.sql                           >> tabelle2.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateKinds.sql                                      >> tabelle2.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateMenu.sql                                       >> tabelle2.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateProgettiViews.sql                              >> tabelle2.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateProgettoDetail.sql                             >> tabelle2.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getcontratti.sql                                       >> tabelle2.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getcostididattica.sql                                  >> tabelle2.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getdocentiperssd.sql                                   >> tabelle2.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getoreaffidamentoperanno.sql                           >> tabelle2.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getregistrydocentiamministrativi.sql                   >> tabelle2.sql

type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateAssetdiaryoraview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateLezioneView.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateRendicontattivitaprogettooraview.sql           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateTimesheetView.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\vs_casualcontractworkpackageview.sql                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\vs_invoicedetailexpworkpackageview.sql                 >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\vs_payrollworkpackageview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\vs_wageadditionworkpackageview.sql                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accmotivedefaultview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accmotivesegview.sql                                 >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accordoscambiomisegview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accreditokinddefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_addresssegview.sql                                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentodefaultview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentokinddefaultview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentosegview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ambitoareadiscdefaultview.sql                        >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_aoodefaultview.sql                                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_aooprincview.sql                                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_appelloazionekinddefaultview.sql                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_appellodefaultview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_appelloerogataview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_appellokinddefaultview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_areadidatticadefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetacquiresegview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetsegview.sql                                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assicurazionedefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_atecodefaultview.sql                                 >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformappelloview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformdefaultview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformerogataview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformgruppoview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformpropedview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_auladefaultview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_aulakinddefaultview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_aulaseg_childview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_bandodssegview.sql                                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_bandomisegview.sql                                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_bandomobilitaintkinddefaultview.sql                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_canaleerogataview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ccnldefaultview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_cefrdefaultview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_cefrlangleveldefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_changeskinddefaultview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_classconsorsualedefaultview.sql                      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_classescuoladefaultview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_classescuolakinddefaultview.sql                      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_contrattokinddefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_convenzionesegview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiodefaultview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiodotmasview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudioingressoview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiokinddefaultview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiolivellodefaultview.sql                    >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudionormadefaultview.sql                      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiostatoview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_costoscontodefkinddefaultview.sql                    >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_costoscontodefmoreview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_costoscontodefscontiview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_decadenzasegview.sql                                 >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_deliberasegview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiaraltrekinddefaultview.sql                      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiaraltre_segview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiaraltrititoli_segview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiardisabilkinddefaultview.sql                    >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiardisabilsuppkinddefaultview.sql                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiardisabil_seganagstuview.sql                    >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiardisabil_segview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiarisee_seganagstuview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiarisee_segview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiarkinddefaultview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiarsegview.sql                                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiartitolo_segview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_diderogdefaultview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogannodefaultview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogdefaultview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogdotmasview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogingressoview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogoridefaultview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogorisceltacorsoview.sql                        >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogporzannodefaultview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogstatoview.sql                                 >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_duratakinddefaultview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_edificiodefaultview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_edificioseg_childview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_erogazkinddefaultview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_esonerocarrieraview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_esonerodefaultview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_esonerodisabilview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_esonerotitolostudioview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_expensesegview.sql                                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_fasciaiseedefdefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_fasciaiseedefmoreview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_fasciaiseedefscontiview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_fonteindicebibliometricosegview.sql                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_citydefaultview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_citysegchildview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_citysegview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_countrysegchildview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_countrysegview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_nationlingueview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_nationsegchildview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_nationsegview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_regionsegview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getcostididatticadefaultview.sql                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getcostididatticaerogataview.sql                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getdocentiperssdsegview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getregistrydocentiamministratividefaultview.sql      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_graduatoriavardefaultview.sql                        >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_inquadramentodefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_insegndefaultview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_insegnintegdefaultview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_inventorytreesegview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionebmiattachsegview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionebmisegview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionedefaultview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionedidprogview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionedotmasview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneingressoview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneseganagstuaccview.sql                      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneseganagstumastview.sql                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneseganagstusingview.sql                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneseganagstustatoview.sql                    >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneseganagstuview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionesegview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionestatoview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaattachsegview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzacert_segview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaeq_segview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_seganagstupreview.sql                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_seganagsturinview.sql                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_seganagstuview.sql                        >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_segpreview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_segrinview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_segview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzakinddefaultview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzapas_seganagstuview.sql                        >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzarin_segview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaseganagstusonpreview.sql                      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzasosp_segview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzatru_segview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_itinerationsegview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_learningagrstudsegview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_learningagrtrainersegview.sql                        >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_nacedefaultview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_naturagiurdefaultview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_nullaostaimm_seganagstupreview.sql                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_nullaostaimm_seganagsturinview.sql                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_nullaostaimm_seganagstuview.sql                      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ofakinddefaultview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_orakindsegview.sql                                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_pagamentokinddefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_pettycashsegview.sql                                 >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_pianostudiosegstudview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_pianostudiostatusdefaultview.sql                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_praticasegstudview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettoactivitykinddefaultview.sql                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettokindsegview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettotipocostosegview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_protocollodockindsegview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_protocollorifkindsegview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_protocollosegview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_provaaulaview.sql                                    >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_provadefaultview.sql                                 >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_provadotmasview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_provaingressoview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_provastatoview.sql                                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazkinddefaultview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_questionariodefaultview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_questionariodomkinddefaultview.sql                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_questionariokinddefaultview.sql                      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ratadefdefaultview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ratadefmoreview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ratadefscontiview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ratakinddefaultview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryaddresssegview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryaddressuserview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativiview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryaziendeview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryclassaziendeview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryclassdefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryclasspersoneview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydefaultview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocentiview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistitutiesteriview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistitutiview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistituti_princview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryprogfinbandosegview.sql                      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryprogfinsegview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrystudentiview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryuserview.sql                                 >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontaltrokinddefaultview.sql                    >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagammview.sql             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagview.sql                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettosegview.sql                 >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sasddefaultview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sasdgruppodefaultview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sededefaultview.sql                                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sedeseg_childview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sedeseg_child_aziendaview.sql                        >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sessionedefaultview.sql                              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sessionekinddefaultview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_settoreercsegprogview.sql                            >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_settoreercsegview.sql                                >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentodefaultview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentodidprogview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoesitodefaultview.sql                     >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoingressoview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoseganagstuaccview.sql                    >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoseganagstuconsmastview.sql               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoseganagstusingview.sql                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoseganagstustatoview.sql                  >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoseganagstuview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentosegconsview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentosegstudview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_stipendiokinddefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturadefaultview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturakinddefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturaprincview.sql                               >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturaseg_childview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_studdirittokinddefaultview.sql                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_studprenotkinddefaultview.sql                        >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tassaconfdefaultview.sql                             >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tassaconfkinddefaultview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tassacsingconfdefaultview.sql                        >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tassaiscrizioneconfdefaultview.sql                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tassaistanzaconfdefaultview.sql                      >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_taxsegview.sql                                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tipoattformdefaultview.sql                           >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tipologiastudentesegview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tirociniocandidaturakinddefaultview.sql              >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tirocinioprogettosegview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tirociniopropostosegview.sql                         >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tirociniostatodefaultview.sql                        >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_titolostudiodocentiview.sql                          >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_upbdefaultview.sql                                   >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_upbsegview.sql                                       >> tabelle3.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_workpackagesegview.sql                               >> tabelle3.sql