type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateMenu.sql							>> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateWebList_Redir.sql                     >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql                                  >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoasset.sql                             >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettokind.sql                              >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocosto.sql                         >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokind.sql                     >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindtax.sql                  >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostotax.sql                      >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudr.sql                               >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembro.sql                         >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembrokind.sql                     >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogetto.sql                 >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tax.sql                                       >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accmotivesegview.sql                        >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettoassetdefaultview.sql                >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettokindsegview.sql                     >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql                         >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettoudrmembrokinddefaultview.sql        >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettosegview.sql        >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_taxsegview.sql                              >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_workpackagesegview.sql                      >> tabelle20201118.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackage.sql                               >> tabelle20201118.sql
