type D:\progetti\Portale\client\app_segreterie\ScriptSQL\asset.sql										>> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiary.sql                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateMenu.sql                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateWebList_Redir.sql                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql                                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattach.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkind.sql                       >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkindprogettostatuskind.sql     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettokind.sql                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokind.sql                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokindprogettostatuskind.sql      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicaz.sql                                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazregistry_docenti.sql                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_amministrativi.sql                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_docenti.sql                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogetto.sql                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetsegview.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettokindsegview.sql                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazdefaultview.sql                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazdocentiview.sql                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativiview.sql             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocentiview.sql                    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagammview.sql   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagview.sql      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_workpackagesegview.sql                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackage.sql                              >> tabelle.sql
