
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamento.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentoattach.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentocaratteristica.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentocaratteristicaora.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ambitoareadisc.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiary.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiaryora.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\aula.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ccnlregistry_aziende.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\contratto.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\contrattokind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudio.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudiocaratteristica.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\currency.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprog.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\edificio.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\fonteindicebibliometrico.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\inventorytree.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizione.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istitutoprinc.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoactivitykind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoasset.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattach.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkindprogettostatuskind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettobudget.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettobudgetvariazione.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettocosto.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettokind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoproroga.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoregistry_aziende.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettorp.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettosettoreerc.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettostatuskind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotesto.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokindprogettostatuskind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocosto.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostoaccmotive.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostocontrattokind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostoinventorytree.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindaccmotive.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindcontrattokind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindinventorytree.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindtax.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostotax.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudr.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembro.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembrokind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollo.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodestinatario.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodoc.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodocelement.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodockind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollorifkind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\prova.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicaz.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazkeyword.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazkind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazkindpublicaz.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazregistry_aziende.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazregistry_docenti.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryaddress.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryclass.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfin.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfinbando.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfinbandoattach.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryreference.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_amministrativi.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_aziende.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_docenti.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_istituti.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_istitutiesteri.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicont.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontaltro.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogetto.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogettoora.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontlezionestud.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sasd.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sede.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\settoreerc.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sospensione.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\stipendiokind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\struttura.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\strutturakind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tax.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tipoattform.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\titolostudio.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackage.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackagekind.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackageupb.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetdiarydocview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_GenerateTimesheetView.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativiview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocentiview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistituti_princview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagammview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettodocview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettosegview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_settoreercsegview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_workpackagesegview.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_compute_assetdiaryora.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_GenerateProgettoDetail.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateMetaData.sql >> tabelle20210213-23.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateWebList_Redir.sql >> tabelle20210213-23.sql
