
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\assetdiary.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\assetdiary.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\assetdiary.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\assetdiaryora.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\assetdiaryora.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\assetdiaryora.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progetto.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progetto.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progetto.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progettoasset.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progettoasset.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progettoasset.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progettobudget.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progettobudget.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progettobudget.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progettocosto.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progettocosto.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\progettocosto.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registrationuser.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registrationuser.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registrationuser.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registrationuserflowchart.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registrationuserflowchart.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registrationuserflowchart.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registrationuserstatus.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registrationuserstatus.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registrationuserstatus.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registry_amministrativi.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registry_amministrativi.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registry_amministrativi.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registry_docenti.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registry_docenti.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\registry_docenti.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicont.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicont.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicont.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontaltro.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontaltro.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontaltro.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogetto.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogetto.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogetto.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogettoitineration.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogettoitineration.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogettoitineration.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogettoora.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogettoora.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogettoora.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogettoyear.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogettoyear.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\rendicontattivitaprogettoyear.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\sal.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\sal.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\sal.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\salassetdiaryora.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\salassetdiaryora.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\salassetdiaryora.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\salprogettocosto.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\salprogettocosto.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\salprogettocosto.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\salrendicontattivitaprogettoora.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\salrendicontattivitaprogettoora.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\salrendicontattivitaprogettoora.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\workpackage.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\workpackage.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\workpackage.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\workpackageupb.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\workpackageupb.vocdbo.sql  >> vocdbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\workpackageupb.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_assetdiarydocview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_assetdiarydocview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_assetdiaryorasegsalview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_assetdiaryorasegsalview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_assetdiaryorasegview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_assetdiaryorasegview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_assetdiaryseganagview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_assetdiaryseganagview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_assetdiarysegview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_assetdiarysegview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_flowchartsegview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_flowchartsegview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_istanzaeq_segview.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_istanzaeq_segview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_progettocostosegprgview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_progettocostosegprgview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_progettocostosegsalview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_progettocostosegsalview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_progettocostosegview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_progettocostosegview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_progettosegview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_progettosegview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_protocollosegview.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_protocollosegview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_registrationuserauthview.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_registrationuserauthview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_registrationuserusrview.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_registrationuserusrview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_registryamministrativiview.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_registryamministrativiview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_registrydocentiview.dbo.sql  >> dbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_registrydocentiview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettoanagammview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettoanagammview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettoanagview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettoanagview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettodocview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettodocview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettoorasegsalview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettoorasegsalview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettoorasegview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettoorasegview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettosegview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_rendicontattivitaprogettosegview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_saldefaultview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_saldefaultview.vocndbo.sql  >> vocndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_workpackagesegview.ndbo.sql  >> ndbo20210323.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_workpackagesegview.vocndbo.sql  >> vocndbo20210323.sql

