
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamento.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamento.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamento.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentoattach.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentoattach.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentoattach.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentocaratteristica.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentocaratteristica.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentocaratteristica.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentocaratteristicaora.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentocaratteristicaora.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentocaratteristicaora.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\affidamentokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\ambitoareadisc.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\ambitoareadisc.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\ambitoareadisc.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\annoaccademico.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\annoaccademico.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\annoaccademico.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\aoo.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\aoo.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\aoo.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\areadidattica.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\areadidattica.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\areadidattica.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\assetdiary.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\assetdiary.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\assetdiary.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\assetdiaryora.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\assetdiaryora.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\assetdiaryora.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\ateco.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\ateco.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\ateco.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\attach.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\attach.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\attach.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\attivform.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\attivform.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\attivform.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\aula.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\aula.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\aula.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\canale.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\canale.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\canale.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\ccnlregistry_aziende.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\ccnlregistry_aziende.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\ccnlregistry_aziende.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\classconsorsuale.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\classconsorsuale.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\classconsorsuale.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\contratto.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\contratto.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\contratto.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\contrattokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\contrattokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\contrattokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\convenzione.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\convenzione.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\convenzione.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\corsostudio.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\corsostudio.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\corsostudio.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\corsostudiocaratteristica.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\corsostudiocaratteristica.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\corsostudiocaratteristica.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\diderog.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\diderog.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\diderog.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprog.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprog.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprog.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogaccesso.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogaccesso.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogaccesso.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didproganno.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didproganno.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didproganno.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogcurr.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogcurr.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogcurr.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didproggrupp.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didproggrupp.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didproggrupp.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprognumchiusokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprognumchiusokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprognumchiusokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogori.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogori.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogori.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogporzanno.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogporzanno.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogporzanno.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogsuddannokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogsuddannokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\didprogsuddannokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\duratakind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\duratakind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\duratakind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\edificio.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\edificio.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\edificio.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\erogazkind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\erogazkind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\erogazkind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\esoneroanskind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\esoneroanskind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\esoneroanskind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\fonteindicebibliometrico.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\fonteindicebibliometrico.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\fonteindicebibliometrico.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\graduatoria.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\graduatoria.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\graduatoria.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\inquadramento.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\inquadramento.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\inquadramento.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegn.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegn.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegn.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegncaratteristica.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegncaratteristica.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegncaratteristica.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegninteg.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegninteg.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegninteg.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegnintegcaratteristica.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegnintegcaratteristica.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\insegnintegcaratteristica.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\iscrizione.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\iscrizione.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\iscrizione.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\iscrizioneanno.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\iscrizioneanno.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\iscrizioneanno.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\istattitolistudio.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\istattitolistudio.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\istattitolistudio.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\istitutokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\istitutokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\istitutokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\istitutoprinc.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\istitutoprinc.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\istitutoprinc.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\lezione.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\lezione.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\lezione.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\menuweb.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\menuweb.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\menuweb.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\nace.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\nace.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\nace.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\naturagiur.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\naturagiur.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\naturagiur.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\numerodip.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\numerodip.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\numerodip.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progetto.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progetto.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progetto.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoactivitykind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoactivitykind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoactivitykind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoasset.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoasset.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoasset.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoattach.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoattach.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoattach.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoattachkind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoattachkind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoattachkind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoattachkindprogettostatuskind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoattachkindprogettostatuskind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoattachkindprogettostatuskind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettobudget.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettobudget.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettobudget.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettobudgetvariazione.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettobudgetvariazione.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettobudgetvariazione.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettocosto.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettocosto.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettocosto.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoproroga.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoproroga.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoproroga.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoregistry_aziende.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoregistry_aziende.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoregistry_aziende.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettorp.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettorp.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettorp.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettosettoreerc.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettosettoreerc.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettosettoreerc.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettostatuskind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettostatuskind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettostatuskind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotesto.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotesto.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotesto.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotestokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotestokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotestokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotestokindprogettostatuskind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotestokindprogettostatuskind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotestokindprogettostatuskind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotimesheet.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotimesheet.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotimesheet.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotimesheetprogetto.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotimesheetprogetto.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotimesheetprogetto.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocosto.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocosto.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocosto.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostoaccmotive.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostoaccmotive.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostoaccmotive.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostocontrattokind.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostocontrattokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostocontrattokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostoinventorytree.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostoinventorytree.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostoinventorytree.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindaccmotive.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindaccmotive.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindaccmotive.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindcontrattokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindcontrattokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindcontrattokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindinventorytree.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindinventorytree.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindinventorytree.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindtax.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindtax.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostokindtax.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostotax.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostotax.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettotipocostotax.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoudr.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoudr.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoudr.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoudrmembro.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoudrmembro.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoudrmembro.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoudrmembrokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoudrmembrokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\progettoudrmembrokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollo.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollo.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollo.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodestinatario.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodestinatario.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodestinatario.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodoc.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodoc.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodoc.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodocelement.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodocelement.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodocelement.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodockind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodockind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollodockind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollorifkind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollorifkind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\protocollorifkind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\prova.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\prova.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\prova.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicaz.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicaz.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicaz.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazkeyword.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazkeyword.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazkeyword.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazkind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazkind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazkind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazkindpublicaz.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazkindpublicaz.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazkindpublicaz.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazregistry_aziende.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazregistry_aziende.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazregistry_aziende.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazregistry_docenti.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazregistry_docenti.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\publicazregistry_docenti.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registryprogfin.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registryprogfin.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registryprogfin.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registryprogfinbando.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registryprogfinbando.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registryprogfinbando.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registryprogfinbandoattach.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registryprogfinbandoattach.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registryprogfinbandoattach.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_amministrativi.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_amministrativi.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_amministrativi.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_aziende.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_aziende.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_aziende.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_docenti.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_docenti.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_docenti.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_istituti.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_istituti.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_istituti.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_istitutiesteri.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_istitutiesteri.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_istitutiesteri.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_studenti.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_studenti.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\registry_studenti.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicont.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicont.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicont.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontaltro.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontaltro.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontaltro.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontattivitaprogetto.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontattivitaprogetto.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontattivitaprogetto.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontattivitaprogettoora.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontattivitaprogettoora.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontattivitaprogettoora.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontlezionestud.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontlezionestud.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\rendicontlezionestud.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sasd.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sasd.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sasd.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sede.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sede.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sede.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sessione.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sessione.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sessione.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sessionekind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sessionekind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sessionekind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\settoreerc.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\settoreerc.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\settoreerc.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sospensione.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sospensione.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\sospensione.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\statuskind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\statuskind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\statuskind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\stipendiokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\stipendiokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\stipendiokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\struttura.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\struttura.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\struttura.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\strutturakind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\strutturakind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\strutturakind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\studdirittokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\studdirittokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\studdirittokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\studprenotkind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\studprenotkind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\studprenotkind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\tipoattform.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\tipoattform.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\tipoattform.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\titolokind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\titolokind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\titolokind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\titolostudio.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\titolostudio.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\titolostudio.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\workpackage.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\workpackage.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\workpackage.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\workpackagekind.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\workpackagekind.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\workpackagekind.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\workpackageupb.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\workpackageupb.vocdbo.sql  >> vocdbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\workpackageupb.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\year.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\year.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_accmotivedefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_accmotivedefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_accmotivesegview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_accmotivesegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_affidamentodefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_affidamentodefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_affidamentodocview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_affidamentodocview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_affidamentosegview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_affidamentosegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_assetdiarydocview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_assetdiarydocview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_assetdiaryoraview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_assetdiaryoraview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_assetsegview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_assetsegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_attivformappelloview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_attivformappelloview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_attivformdefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_attivformdefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_attivformerogataview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_attivformerogataview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_attivformgruppoview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_attivformgruppoview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_attivformpropedview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_attivformpropedview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_canaleerogataview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_canaleerogataview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_contrattokinddefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_contrattokinddefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_corsostudiodotmasview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_corsostudiodotmasview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_corsostudiostatoview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_corsostudiostatoview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_diderogdefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_diderogdefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_didprogdefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_didprogdefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_didprogdotmasview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_didprogdotmasview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_didprogstatoview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_didprogstatoview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_duratakinddefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_duratakinddefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_edificioseg_childview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_edificioseg_childview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_fonteindicebibliometricosegview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_fonteindicebibliometricosegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_GenerateTimesheetView.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_GenerateTimesheetView.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_geo_cityseg5view.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_geo_cityseg5view.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_getcontratti.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_getcontratti.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_getprogettocostoview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_getprogettocostoview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_getregistrydocentiamministrativi.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_getregistrydocentiamministrativi.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_getregistrydocentiamministratividefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_getregistrydocentiamministratividefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_inventorytreesegview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_inventorytreesegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettoactivitykinddefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettoactivitykinddefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettoassetdefaultview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettoassetdefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettokindsegview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettokindsegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettosegview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettosegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettotipocostosegview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettotipocostosegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettoudrmembrokinddefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_progettoudrmembrokinddefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_publicazdefaultview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_publicazdefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_publicazdocentiview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_publicazdocentiview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_publicazkinddefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_publicazkinddefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryaddresssegview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryaddresssegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryamministrativiview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryamministrativiview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryamministrativi_personaleview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryamministrativi_personaleview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryaziendeview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryaziendeview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryclassaziendeview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryclassaziendeview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryclassdefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryclassdefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registrydocentiview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registrydocentiview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registrydocenti_docview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registrydocenti_docview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryistitutiesteriview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryistitutiesteriview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryistitutiview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryistitutiview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryistituti_princview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryistituti_princview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryprogfinbandosegview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryprogfinbandosegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryprogfinsegview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_registryprogfinsegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_rendicontattivitaprogettoanagammview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_rendicontattivitaprogettoanagammview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_rendicontattivitaprogettoanagview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_rendicontattivitaprogettoanagview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_rendicontattivitaprogettodocview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_rendicontattivitaprogettodocview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_rendicontattivitaprogettooraview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_rendicontattivitaprogettooraview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_rendicontattivitaprogettosegview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_rendicontattivitaprogettosegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_sededefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_sededefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_sedeseg_childview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_sedeseg_childview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_sedeseg_child_aziendaview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_sedeseg_child_aziendaview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_settoreercsegprogview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_settoreercsegprogview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_settoreercsegview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_settoreercsegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_stipendiokinddefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_stipendiokinddefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_strutturadefaultview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_strutturadefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_strutturakinddefaultview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_strutturakinddefaultview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_strutturaprincview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_strutturaprincview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_taxsegview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_taxsegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_titolostudiodocentiview.dbo.sql  >> dbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_titolostudiodocentiview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_upbsegview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_upbsegview.vocndbo.sql  >> vocndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_workpackagesegview.ndbo.sql  >> ndbo20210303.sql
type D:\progetti\Portale\client\app_segreterie\ScriptLU\v_workpackagesegview.vocndbo.sql  >> vocndbo20210303.sql

