type D:\progetti\Portale\client\VisualMDLW\ScriptSQL\virtualuser.sql >> tabelle20201126S.sql
type D:\progetti\Portale\client\VisualMDLW\ScriptSQL\dbaccess.sql >> tabelle20201126S.sql
type D:\progetti\Portale\client\VisualMDLW\ScriptSQL\menuweb_addentry.sql >> tabelle20201126S.sql
type D:\progetti\Portale\client\VisualMDLW\ScriptSQL\GenerateUser.sql >> tabelle20201126S.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateMenu.sql >> tabelle20201126S.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateSecurity.sql >> tabelle20201126S.sql

type D:\progetti\Portale\client\app_segreterie\ScriptSQL\accmotive.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoasset.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettokind.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoregistry_aziende.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocosto.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokind.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindtax.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostotax.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudr.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembro.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembrokind.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accmotivedefaultview.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accmotivesegview.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettokindsegview.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettoudrmembrokinddefaultview.sql >> tabelle20201126.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_taxsegview.sql >> tabelle20201126.sql
