type D:\progetti\Portale\client\app_segreterie\ScriptSQL\annoaccademico.sql							>> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\asset.sql                                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiary.sql                             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiaryora.sql                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateMenu.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateProgettiViews.sql                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateProgettoDetail.sql                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\learningagrkind.sql                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\learningagrtrainerkind.sql                 >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\learningagrtrainervalut.sql                >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql                               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoasset.sql                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattach.sql                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkind.sql                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkindprogettostatuskind.sql   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettobudget.sql                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettocosto.sql                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettokind.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoproroga.sql                        >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoregistry_aziende.sql               >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettosettoreerc.sql                     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotesto.sql                          >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokind.sql                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokindprogettostatuskind.sql    >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocosto.sql                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostoaccmotive.sql             >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostocontrattokind.sql         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostoinventorytree.sql         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostotax.sql                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudr.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembro.sql                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogetto.sql              >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogettoora.sql           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getcontratti.sql                           >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getcostididattica.sql                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetsegview.sql                         >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettokindsegview.sql                  >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql                      >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettosegview.sql     >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_workpackagesegview.sql                   >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackage.sql                            >> tabelle.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackageupb.sql                         >> tabelle.sql
type D:\progetti\Portale\client\VisualMDLW\ScriptSQL\menuweb_addentry.sql                        	>> tabelle.sql