
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentokind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ambitoareadisc.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\annoaccademico.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\appello.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\appelloattivform.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ateco.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attivformvalutazionekind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\aulakind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandodsiscresitokind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\bandomi.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\classescuola.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\classescuolacaratteristica.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\contrattokindperiodo.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudiocaratteristica.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\costoscontodefdettagliokind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\costoscontodefkind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiaraltrekind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\dichiarkind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogcurrcaratteristica.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\erogazkind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\expenseview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\GenerateKinds.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getcostididattica.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getdocentiperssd.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getprogettocostoview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getregistrydocentiamministrativi.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizionebmi.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanza.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istanza_imm.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\itineration.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\learningagrstud.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\learningagrtrainer.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\location.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\metadatatables.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\mutuazionecaratteristica.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\nace.sql >> tabelle20210209.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\pettycash.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\pianostudioattivform.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\prenotappello.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattach.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkindprogettostatuskind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettokind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettorp.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettosettoreerc.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokindprogettostatuskind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotimesheet.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotimesheetprogetto.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocosto.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\programmami.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\provaaula.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\questionariodomrisp.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_amministrativi.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_docenti.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_studenti.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontaltrokind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sasdgruppo.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\settoreerc.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sospensione.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sostenimentoesito.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\strutturakind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tipoattform.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirocinioapprkind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirociniodiario.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tirociniorelazione.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\valutazionekind.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\virtualuser.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accmotivedefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accordoscambiomidettazsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accordoscambiomidettsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accordoscambiomisegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accreditokinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_addresssegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentokinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ambitoareadiscdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_aoodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_aooprincview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_appelloazionekinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_appellodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_appelloerogataview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_appellokinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_areadidatticadefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetacquiresegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assicurazionedefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_atecodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformappelloview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformerogataview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformgruppoview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformpropedview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_auladefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_aulakinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_aulaseg_childview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_bandodsiscresitokinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_bandodssegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_bandodsserviziosegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_bandomisegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_bandomobilitaintkinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ccnldefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_cefrdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_changeskinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_classconsorsualedefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_classescuoladefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_classescuolakinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_convenzionesegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiokinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiolivellodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudionormadefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_costoscontodefkinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_costoscontodefmoreview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_costoscontodefscontiview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_decadenzasegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_deliberasegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiaraltrekinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiaraltre_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiaraltrititoli_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiardisabilkinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiardisabilsuppkinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiardisabil_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiarisee_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiarkinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiarsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiartitolo_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogannodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogoridefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogorisceltacorsoview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogporzannodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_duratakinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_edificiodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_erogazkinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_esonerocarrieraview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_esonerodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_esonerodisabilview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_esonerotitolostudioview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_expensesegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_expenseviewdettaglio_dei_costiview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_fasciaiseedefmoreview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_fasciaiseedefscontiview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_GenerateRendicontattivitaprogettooraview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_GenerateTimesheetView.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_citydefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_citysegchildview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_citysegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_countrysegchildview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_countrysegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_nationlingueview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_nationsegchildview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_nationsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_regionsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getcontratti.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getcostididatticadefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getdocentiperssdsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getregistrydocentiamministratividefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_graduatoriavardefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_inquadramentodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_insegndefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_insegnintegdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionebmisegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionedefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionedidprogview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionedotmasview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizioneingressoview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionesegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_iscrizionestatoview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaattachsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzacert_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaeq_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_seganagstupreview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_seganagsturinview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_seganagstuview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_segpreview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_segrinview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaimm_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzakinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzapas_seganagstuview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzarin_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzaseganagstusonpreview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzasosp_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_istanzatru_segview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_itinerationsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_learningagrstudsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_learningagrtrainersegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_locationdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_nacedefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_naturagiurdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_nullaostaimm_seganagstupreview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_nullaostaimm_seganagsturinview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_nullaostaimm_seganagstuview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ofakinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_orakindsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_pagamentokinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_pettycashsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_pianostudiosegstudview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_pianostudiostatusdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_praticaseganagstuview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_praticasegstudview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettokindsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_protocollodockindsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_protocollorifkindsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_protocollosegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_provaaulaview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_provadefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_provadotmasview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_provaingressoview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_provastatoview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazdocentiview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_questionariodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_questionariodomkinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_questionariokinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ratadefmoreview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ratadefscontiview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_ratakinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryaddressuserview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativiview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativi_personaleview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryclassaziendeview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryclasspersoneview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocentiview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocenti_docview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistituti_princview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrystudentiview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryuserview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontaltrokinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_saldefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sasddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sasdgruppodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sessionedefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sessionekinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_settoreercsegprogview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_settoreercsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentodidprogview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoesitodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoingressoview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoseganagstuaccview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoseganagstuconsmastview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoseganagstusingview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoseganagstustatoview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentoseganagstuview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentosegconsview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sostenimentosegstudview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturakinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturaseg_childview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_studdirittokinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_studprenotkinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tassaconfdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tassaconfkinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tassacsingconfdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tassaiscrizioneconfdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tassaistanzaconfdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tipoattformdefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tirociniocandidaturakinddefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tirocinioprogettosegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tirociniopropostosegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_tirociniostatodefaultview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_upbsegview.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\year.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_compute_assetdiaryora.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_GenerateDidProgCurricula.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_GenerateProgettoDetail.sql >> tabelle20210209.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateMenu.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateMetaData.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateRules.sql >> tabelle20210209.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateSecurity.sql >> tabelle20210209.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateSecurity2021.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateWebList_Redir.sql >> tabelle20210209.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_setupTipiProgetti.sql >> tabelle20210209.sql
