
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamento.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentoattach.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentocaratteristica.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamentocaratteristicaora.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ambitoareadisc.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\annoaccademico.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\aoo.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiary.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiaryora.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\areadidattica.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ateco.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attach.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attivform.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\aula.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\ccnlregistry_aziende.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\canale.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\classconsorsuale.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\contratto.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\contrattokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\convenzione.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudio.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\corsostudiocaratteristica.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\currency.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\diderog.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprog.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogaccesso.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didproganno.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogcurr.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didproggrupp.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogori.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprognumchiusokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogporzanno.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprogsuddannokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\duratakind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\edificio.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\erogazkind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\esoneroanskind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\fonteindicebibliometrico.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\graduatoria.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\insegn.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\insegncaratteristica.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\insegninteg.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\insegnintegcaratteristica.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\inquadramento.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizione.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\iscrizioneanno.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istattitolistudio.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istitutokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\istitutoprinc.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\lezione.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\menuweb.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\nace.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\naturagiur.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\numerodip.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoactivitykind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoasset.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattach.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoattachkindprogettostatuskind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettobudget.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettobudgetvariazione.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettocosto.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoproroga.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoregistry_aziende.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettorp.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettosettoreerc.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettostatuskind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotesto.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotestokindprogettostatuskind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotimesheet.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotimesheetprogetto.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocosto.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostoaccmotive.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostocontrattokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostoinventorytree.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindaccmotive.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindcontrattokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindinventorytree.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokindtax.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostotax.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudr.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembro.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembrokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollo.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodestinatario.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodoc.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodocelement.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollodockind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\protocollorifkind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\prova.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicaz.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazkeyword.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazkind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazkindpublicaz.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazregistry_aziende.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\publicazregistry_docenti.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfin.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfinbando.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registryprogfinbandoattach.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_amministrativi.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_aziende.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_docenti.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_istituti.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_istitutiesteri.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_studenti.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicont.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontaltro.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogetto.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogettoora.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontlezionestud.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sasd.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sede.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sessione.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sessionekind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\settoreerc.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sospensione.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\statuskind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\stipendiokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\struttura.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\strutturakind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\studdirittokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\studprenotkind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tax.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\tipoattform.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\titolokind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\titolostudio.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackage.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackagekind.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackageupb.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\year.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accmotivedefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_accmotivesegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentodefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentodocview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentosegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetdiarydocview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetdiaryoraview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetsegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformappelloview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformdefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformerogataview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformgruppoview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformpropedview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_canaleerogataview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_contrattokinddefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiodotmasview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_corsostudiostatoview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_diderogdefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogdefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogdotmasview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogstatoview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_edificioseg_childview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_fonteindicebibliometricosegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_GenerateTimesheetView.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_geo_cityseg5view.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getcontratti.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getprogettocostoview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_getregistrydocentiamministratividefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_inventorytreesegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_duratakinddefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettoactivitykinddefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettoassetdefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettokindsegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettotipocostosegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettoudrmembrokinddefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazdefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazdocentiview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_publicazkinddefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryaddresssegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativiview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativi_personaleview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryaziendeview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryclassaziendeview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryclassdefaultview.sql >> tabelle-LU-20210225.sql
REM type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocentiview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocenti_docview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistituti_princview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistitutiesteriview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryistitutiview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryprogfinbandosegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryprogfinsegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagammview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettodocview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettooraview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettosegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sededefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sedeseg_child_aziendaview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_sedeseg_childview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_settoreercsegprogview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_settoreercsegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_stipendiokinddefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturadefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturakinddefaultview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_strutturaprincview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_taxsegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_titolostudiodocentiview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_upbsegview.sql >> tabelle-LU-20210225.sql
REM v_upbdefaultview
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_workpackagesegview.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_compute_assetdiaryora.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_GenerateProgettoDetail.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateMetaData.sql >> tabelle-LU-20210225.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateWebList_Redir.sql >> tabelle-LU-20210225.sql
