
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\analisiannuale.vocndbo.sql  >> vocndbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\analisiannuale.vocdbo.sql  >> vocdbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\analisiannuale.dbo.sql  >> dbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\stipendioannuo.vocndbo.sql  >> vocndbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\stipendioannuo.vocdbo.sql  >> vocdbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\stipendioannuo.dbo.sql  >> dbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsconfigurazionecostopuntoincr.vocndbo.sql  >> vocndbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsconfigurazionecostopuntoincr.vocdbo.sql  >> vocdbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsconfigurazionecostopuntoincr.dbo.sql  >> dbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsconfigurazionecostopunto.vocndbo.sql  >> vocndbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsconfigurazionecostopunto.vocdbo.sql  >> vocdbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsconfigurazionecostopunto.dbo.sql  >> dbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsconfigurazione.vocndbo.sql  >> vocndbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsconfigurazione.vocdbo.sql  >> vocdbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsconfigurazione.dbo.sql  >> dbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsbilancio.vocndbo.sql  >> vocndbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsbilancio.vocdbo.sql  >> vocdbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsbilancio.dbo.sql  >> dbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsassunzioni.vocndbo.sql  >> vocndbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsassunzioni.vocdbo.sql  >> vocdbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\pcsassunzioni.dbo.sql  >> dbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_perfcomportamentodefaultview.vocndbo.sql  >> vocndbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_perfcomportamentodefaultview.dbo.sql  >> dbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_pcsconfigurazionecostopuntoincrdefaultview.vocndbo.sql  >> vocndbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_pcsconfigurazionecostopuntoincrdefaultview.dbo.sql  >> dbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_analisiannualedefaultview.vocndbo.sql  >> vocndbo20211020.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_analisiannualedefaultview.dbo.sql  >> dbo20211020.sql