
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\affidamento.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiary.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\canale.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\diderog.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoasset.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettobudget.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettobudgetvariazione.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettocosto.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettokind.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocosto.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettotipocostokind.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudr.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettoudrmembro.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_amministrativi.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_docenti.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogetto.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\rendicontattivitaprogettoora.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\sal.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackage.sql >> tabelle20201212.sql

type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentodefaultview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentodocview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetdiarydocview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_canaleerogataview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_dichiarsegview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_diderogdefaultview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_GenerateProgettiViews.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettokindsegview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativiview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocentiview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocenti_docview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagammview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettoanagview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettodocview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_rendicontattivitaprogettosegview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_saldefaultview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_workpackagesegview.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_GenerateCompute_assetdiaryora.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_GenerateProgettoDetail.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_get_assetvalueatdate.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateMenu.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateRules.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateSecurity.sql >> tabelle20201212.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateWebList_Redir.sql >> tabelle20201212.sql
