
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\assetdiary.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\attivform.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\diderog.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didprog.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\didproggrupp.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\getprogettocostoview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progetto.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\progettorp.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_amministrativi.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\registry_docenti.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_affidamentosegview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_assetdiarydocview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformappelloview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformdefaultview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformerogataview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformgruppoview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_attivformpropedview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_diderogdefaultview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_didprogdefaultview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_progettosegview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registryamministrativi_personaleview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_registrydocenti_docview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\v_workpackagesegview.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackage.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\workpackageupb.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_compute_assetdiaryora.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_GenerateDidProgCurricula.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zy_GenerateProgettoDetail.sql >> tabelle20201222.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateMenu.sql >> tabelle20201222S.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateRules.sql >> tabelle20201222S.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateSecurity.sql >> tabelle20201222S.sql
type D:\progetti\Portale\client\app_segreterie\ScriptSQL\zz_GenerateWebList_Redir.sql >> tabelle20201222S.sql
