type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\perfvalutazioneuo.vocdbo.sql  >> vocdbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\strutturaresponsabile.vocndbo.sql  >> vocndbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\strutturaresponsabile.vocdbo.sql  >> vocdbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\strutturaresponsabile.dbo.sql  >> dbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\perfvalutazionepersonale.vocndbo.sql  >> vocndbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\perfvalutazionepersonale.vocdbo.sql  >> vocdbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\perfvalutazionepersonale.dbo.sql  >> dbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_strutturaperfelenchiview.vocndbo.sql  >> vocndbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_strutturaperfelenchiview.ndbo.sql  >> ndbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_perfvalutazioneuodefaultview.vocndbo.sql  >> vocndbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_perfvalutazioneuodefaultview.dbo.sql  >> dbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_afferenzaammview.vocndbo.sql  >> vocndbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_afferenzaammview.dbo.sql  >> dbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_perfvalutazionepersonaledefaultview.vocndbo.sql  >> vocndbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_perfvalutazionepersonaledefaultview.dbo.sql  >> dbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_afferenzastruview.vocndbo.sql  >> vocndbo20220208.sql
type D:\progetti\Portale\client\scripts\app_segreterie\ScriptLU\v_afferenzastruview.dbo.sql  >> dbo20220208.sql
